### PR TITLE
Fix SHOW CREATE TABLE for Elastic Search

### LINKED ISSUE #3385: SHOW CREATE TABLE fails for Elasticearch connector

### PR DESCRIPTION
**Pull request by losipiuk**
Fixes #3385 
Alternative approach to  #3467

### CODE REVIEW

File: presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java [hunk 1]
```diff
@@ -547,14 +547,17 @@ protected Node visitShowCreate(ShowCreate node, Void context)
...
                 String propertyName = propertyEntry.getKey();
                 Object value = propertyEntry.getValue();
-                if (value == null) {
-                    throw new PrestoException(errorCode, format("Property %s for %s cannot have a null value", propertyName, toQualifiedName(objectName, columnName)));
-                }
 
                 PropertyMetadata<?> property = allProperties.get(propertyName);
                 if (property == null) {
-                    throw new PrestoException(errorCode, "No PropertyMetadata for property: " + propertyName);
+                    // ignoring unknown property in SHOW CREATE TABLE
```
Comment (losipiuk) [inline presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java:553]: As an alternative we could only skip properties which are explicitly marked as hidden. This raises the question how to mark those as hidden. If want to go that way, I suggest to encode "hidden" bit in the property name to not blot code too much (e.g. threat properties starting with `_` as hidden). WDYT?

**Comment by martint** [comment]
I don't think we want to do this. See the discussion in https://github.com/prestosql/presto/pull/3467. The proper fix is to keep this information in an internal structure and derive the handle and the metadata from it.

**Comment by losipiuk** [comment]
> I don't think we want to do this. See the discussion in #3467. The proper fix is to keep this information in an internal structure and derive the handle and the metadata from it.

Well - that is very much my intention here. The internal structure is `InternalTableMetadata`. And it exposes two methods:
 * `public ConnectorTableMetadata getConnectorTableMetadata()`
 * `public Map<String, ColumnHandle> getColumnHandles()`

Did I misunderstand something totally. Or are you referring to previous version of this PR which just dropped validation?

**Comment by martint** [comment]
> Or are you referring to previous version of this PR which just dropped validation?

Yes, I didn't realize you changed it since I looked a few hours ago :)

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 2]
```diff
@@ -114,41 +111,90 @@ public ElasticsearchTableHandle getTableHandle(ConnectorSession session, SchemaT
...
-                toColumnMetadata(metadata));
+    private InternalTableMetadata getInternalTableMetadata(String schemaName, String index)
+    {
+        return new InternalTableMetadata(
+                new SchemaTableName(schemaName, index),
+                client.getIndexMetadata(index));
     }
 
-    private List<ColumnMetadata> toColumnMetadata(IndexMetadata metadata)
+    private class InternalTableMetadata
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:130]: Move to the bottom of this file

Comment (martint) [reply presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:130]: There's no good reason for this class to be non-static and for the logic in getColumnMetadata/getColumnHandles to be on-demand. 

Make the class a pure structure (and make it static), and initialize it with the handles and metadata. So, something like:

```java
private InternalTableMetadata makeInternalTableMetadata(SchemaTableName table, IndexMetadata metadata)
{
    // build List<ColumnMetadata> from IndexMetadata
    List<ColumnMetadata> columnMetadata = ...;
    // build Map<String, ColumnHandle> from IndexMetadata
    Map<String, ColumnHandle> columnHandles = ...;

    return new InternalTableMetadata(table, columnMetadata, columnHandles)
}
```

File: presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java [hunk 3]
```diff
@@ -27,7 +27,6 @@
 import org.elasticsearch.client.RestClient;
```
Comment (martint) [inline presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java:27]: This commit needs to come after (or be squashed with) the one that fixes the bug

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java [hunk 4]
```diff
@@ -13,15 +13,14 @@
  */
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java:13]: Add an explanation to the commit message describing why and what bug it fixes

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java (hunk 2 above)
Comment (losipiuk) [reply presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: Done. I added `SchemaTableName` to `InternalTableMetatadata` as you suggest but it is not used in the codebase. It is natural to be there though, and may come handy for object introspection.

File: presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java (hunk 3 above)
Comment (losipiuk) [reply presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java:27]: Order is fine now (it was not before). Github UI ordering is broken, though.

Comment (findepi) [reply presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java:27]: https://gist.github.com/findepi/7abf17c8a26d3b74e8bb9527caadfdbe

Comment (losipiuk) [reply presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java:27]: Yeah - I know. I did not want to kill automation.

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 5]
```diff
@@ -158,9 +158,9 @@ private InternalTableMetadata makeInternalTableMetadata(String schema, String ta
     {
         ImmutableList.Builder<ColumnMetadata> result = ImmutableList.builder();
 
-        result.add(BuiltinColumns.ID.getMetadata());
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: Since this fixes code that was introduced in the previous commit, squash it with that commit.

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 6]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
+    {
+        ElasticsearchTableHandle handle = (ElasticsearchTableHandle) table;
+        return makeInternalTableMetadata(handle.getSchema(), handle.getIndex());
     }
 
-    private List<ColumnMetadata> toColumnMetadata(IndexMetadata metadata)
+    private InternalTableMetadata makeInternalTableMetadata(String schema, String tableName)
     {
-        ImmutableList.Builder<ColumnMetadata> result = ImmutableList.builder();
+        IndexMetadata indexMetadata = client.getIndexMetadata(tableName);
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:132]: This can be renamed to `metadata` for brevity.

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 7]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
+        List<IndexMetadata.Field> indexColumnFields = getColumnFields(indexMetadata);
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:133]: This can be renamed to `fields` for brevity.

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 8]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
+        List<ColumnMetadata> columnMetadata = makeColumnMetadata(indexColumnFields);
+        Map<String, ColumnHandle> columnHandles = makeColumnHandles(indexColumnFields);
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:135]: Inline these variables:

```java
return new InternalTableMetadata(new SchemaTableName(schema, tableName), makeColumnMetadata(fields), makeColumnHandles(fields));
```

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 9]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
 
-        result.add(BuiltinColumns.ID.getMetadata());
-        result.add(BuiltinColumns.SOURCE.getMetadata());
-        result.add(BuiltinColumns.SCORE.getMetadata());
+        return new InternalTableMetadata(new SchemaTableName(schema, tableName), columnMetadata, columnHandles);
+    }
 
-        Map<String, Long> counts = metadata.getSchema()
+    private List<IndexMetadata.Field> getColumnFields(IndexMetadata indexMetadata)
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:140]: This can be renamed to `metadata` for brevity (and undo the rename below)

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 10]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
             Type type = toPrestoType(field);
             if (type == null || counts.get(field.getName().toLowerCase(ENGLISH)) > 1) {
                 continue;
             }
+            result.add(field);
+        }
+        return result.build();
+    }
+
+    private List<ColumnMetadata> makeColumnMetadata(List<IndexMetadata.Field> columnFields)
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:157]: Rename to `fields` for brevity

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 11]
```diff
@@ -120,32 +117,73 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
+        for (IndexMetadata.Field field : columnFields) {
+            result.add(ColumnMetadata.builder()
+                    .setName(field.getName())
+                    .setType(toPrestoType(field))
+                    .build());
+        }
+        return result.build();
+    }
+
+    public Map<String, ColumnHandle> makeColumnHandles(List<IndexMetadata.Field> columnFields)
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java:174]: Rename to `fields` for brevity

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java (hunk 4 above)
Comment (martint) [reply presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java:13]: Typos in the commit message: "Elastic *Seach*" and "*Elatics* Search"

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java (hunk 11 above)
Comment (losipiuk) [reply presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: Also made this one private.
