### PR TITLE
Use CREATE TABE LIKE in MySQL copyTableSchema

### LINKED ISSUE #2251: Execute SQL:create table as select . Error:'Statement violates GTID consistency: CREATE TABLE ... SELECT. '
I've upgraded the presto version to 0.325 recently. 
When I use MySQL connector execute SQL likes "create table new_table as select col1 from old_table" I  got  Error:'Statement violates GTID consistency: CREATE TABLE ... SELECT. '
But in old version 0.192, The SQL works fine. So, any changes in the new version that the type of SQL 
 Is it blocked for some reason? and How to fix it in version 0.325
Thanks in advance！

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #2251

### CODE REVIEW

**Comment by ebyhr** [comment]
@electrum Could you review this PR again? I needed to update `BaseJdbcClient.java` to handle this issue.

File: presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java [hunk 1]
```diff
@@ -657,9 +657,13 @@ public void rollbackCreateTable(JdbcIdentity identity, JdbcOutputTableHandle han
     @Override
     public String buildInsertSql(JdbcOutputTableHandle handle)
     {
+        String columnNames = handle.getColumnNames().stream()
```
Comment (findepi) [inline presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java]: nit: you can inline `columnNames`
