### PR TITLE
Fix reading from large Parquet files

### LINKED ISSUE #2730: ArithmeticException: integer overflow error for certain Parquet files over 2 GB
https://github.com/prestosql/presto/blob/d8e8cc768a13355d146e7db14d084caa84409653/presto-parquet/src/main/java/io/prestosql/parquet/DiskRange.java#L68

Got this Exception
```
io.prestosql.spi.PrestoException: Error opening Hive split s3://xxxx/xxxx/000235_0 (offset=0, length=6678975885): integer overflow
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:251)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:129)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:188)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:108)
	at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:91)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:63)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:240)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:172)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_329____20200203_235109_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at io.prestosql.parquet.DiskRange.span(DiskRange.java:68)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.mergeAdjacentDiskRanges(HdfsParquetDataSource.java:244)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.readSmallDiskRanges(HdfsParquetDataSource.java:170)
	at io.prestosql.plugin.hive.parquet.HdfsParquetDataSource.planRead(HdfsParquetDataSource.java:158)
	at io.prestosql.parquet.reader.ParquetReader.<init>(ParquetReader.java:122)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:208)
```

Seems if a parquet file is larger than 2GB, `DiskRange.span` will throw `Interger Overflow`.

How about use toLongExact instead of toIntExact?

### PR DESCRIPTION
**Pull request by awishnick**
This is a fix for https://github.com/prestosql/presto/issues/2730. When
merging small reads, if the first range and second range are more than 2
GB apart, mergeAdjacentDiskRanges() throw sn ArithmeticException because
merging those two ranges is too big to fit in a DiskRange. The correct
behavior is to not merge those ranges because this implies the ranges
are farther apart than maxReadSizeBytes.

fixes #2730

### CODE REVIEW

File: presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java [hunk 1]
```diff
@@ -241,8 +241,15 @@ public static HdfsParquetDataSource buildHdfsParquetDataSource(
...
         for (int i = 1; i < ranges.size(); i++) {
             DiskRange current = ranges.get(i);
-            DiskRange merged = last.span(current);
-            if (merged.getLength() <= maxReadSizeBytes && last.getEnd() + maxMergeDistanceBytes >= current.getOffset()) {
+            DiskRange merged = null;
+            boolean blockTooLong = false;
+            try {
+                merged = last.span(current);
+            }
+            catch (ArithmeticException e) {
```
Comment (lhofhansl) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java]: Wouldn't it be better to check for the problem condition instead of catching the exception afterwards?

Something like this:
```
            if (Math.max(last.getEnd(), current.getEnd() - Math.min(last.getOffset(), current.getOffset())) <= Integer.MAX_VALUE) {
                DiskRange merged = last.span(current);
                if (merged.getLength() <= maxReadSizeBytes && last.getEnd() + maxMergeDistanceBytes >= current.getOffset()) {
                    last = merged;
                }
            }
```

**Comment by tooptoop4** [comment]
gentle ping @awishnick

**Comment by tooptoop4** [comment]
can the error happen on non-bucketed tables?

**Comment by martint** [comment]
@cla-bot check

File: presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java (hunk 1 above)
Comment (martint) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java]: The issue is that it duplicates the logic of DiskRange, so it's not much better. Alternatively, we could add a method to check it that would result in a valid span, but the current approach is good enough.

**Comment by martint** [comment]
Merged, thanks for your contribution!
