### PR TITLE
Fix unauthorized error by the benchmark driver

### LINKED ISSUE #4923: Running presto-benchmark-driver results in exception - UnexpectedResponseException
Have installed presto version 340 with presto-benchmark-driver ( presto-benchmark-driver-340-executable.jar).
Running the query below results in error:
```
ubuntu@bdbm-prestoco-vm1:/usr/local/presto$ sudo ./presto-benchmark-driver --catalog tpch --schema sf100 --query "select * from nation;" --debug
2020-08-21T15:02:44.891Z        INFO    main    io.airlift.log.Logging  Logging to stderr
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.prestosql.benchmark.driver.RegexTemplate (file:/usr/local/presto-server-340/presto-benchmark-driver) to method java.util.regex.Pattern.namedGroups()
WARNING: Please consider reporting this to the maintainers of io.prestosql.benchmark.driver.RegexTemplate
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
suite   query   compression     format  scale   wallTimeP50     wallTimeMean    wallTimeStd     processCpuTimeP50       processCpuTimeMean      processCpuTimeStd       queryCpuTimeP50 queryCpuTimeMean        queryCpuTimeStd status  error
Exception in thread "main" UnexpectedResponseException{request=Request{uri=http://localhost:8080/v1/service/presto, method=GET, headers={}, bodyGenerator=null, followRedirects=true, preserveAuthorizationOnRedirect=false}, statusCode=401, headers={WWW-Authenticate=[Basic realm="Presto"], Content-Length=[50], Date=[Fri, 21 Aug 2020 15:02:45 GMT], Content-Type=[text/plain;charset=UTF-8]}}
        at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:71)
        at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:531)
        at io.prestosql.benchmark.driver.BenchmarkQueryRunner.getAllNodes(BenchmarkQueryRunner.java:278)
        at io.prestosql.benchmark.driver.BenchmarkQueryRunner.<init>(BenchmarkQueryRunner.java:98)
        at io.prestosql.benchmark.driver.BenchmarkDriver.<init>(BenchmarkDriver.java:50)
        at io.prestosql.benchmark.driver.PrestoBenchmarkDriver.run(PrestoBenchmarkDriver.java:111)
        at io.prestosql.benchmark.driver.PrestoBenchmarkDriver.main(PrestoBenchmarkDriver.java:52)
ubuntu@bdbm-prestoco-vm1:/usr/local/presto$
```

Running the same query using presto client works well 
```
ubuntu@bdbm-prestoco-vm1:/usr/local/presto$ ./prestocli --catalog tpch --schema sf100
presto:sf100> select count(*) from lineitem;
   _col0
-----------
 600037902
(1 row)

Query 20200821_151507_00016_2fnwd, FINISHED, 2 nodes
Splits: 29 total, 29 done (100.00%)
1:09 [600M rows, 0B] [8.76M rows/s, 0B/s]

presto:sf100>
```

### PR DESCRIPTION
**Pull request by Lewuathe**
Although Presto coordinator requires `X-Presto-User` header for the default authentication, BenchmarkDriver fails to send the header when it gets the list of URIs even a user name is specified by the option.

```
$ ./presto-benchmark-driver-341-SNAPSHOT-executable.jar --debug --catalog tpch --user "a"
Exception in thread "main" UnexpectedResponseException{request=Request{uri=http://localhost:8080/v1/service/presto, method=GET, headers={}, bodyGenerator=null, followRedirects=true, preserveAuthorizationOnRedirect=false}, statusCode=401, headers={WWW-Authenticate=[Basic realm="Presto"], Content-Length=[50], Date=[Wed, 19 Aug 2020 06:38:19 GMT], Content-Type=[text/plain;charset=UTF-8]}}
	at io.airlift.http.client.JsonResponseHandler.handle(JsonResponseHandler.java:71)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:549)
	at io.prestosql.benchmark.driver.BenchmarkQueryRunner.getAllNodes(BenchmarkQueryRunner.java:278)
	at io.prestosql.benchmark.driver.BenchmarkQueryRunner.<init>(BenchmarkQueryRunner.java:98)
	at io.prestosql.benchmark.driver.BenchmarkDriver.<init>(BenchmarkDriver.java:50)
	at io.prestosql.benchmark.driver.PrestoBenchmarkDriver.run(PrestoBenchmarkDriver.java:111)
	at io.prestosql.benchmark.driver.PrestoBenchmarkDriver.main(PrestoBenchmarkDriver.java:52)
```

Fixes #4923

### CODE REVIEW

File: presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java [hunk 1]
```diff
@@ -95,7 +96,7 @@ public BenchmarkQueryRunner(int warm, int runs, boolean debug, int maxFailures,
         setupSocksProxy(builder, socksProxy);
         this.okHttpClient = builder.build();
 
-        nodes = getAllNodes(requireNonNull(serverUri, "serverUri is null"));
+        nodes = getAllNodes(requireNonNull(serverUri, "serverUri is null"), user);
```
Comment (sopel39) [inline presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java:99]: use `requireNonNull(user, "user is null")`

File: presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java [hunk 2]
```diff
@@ -271,9 +272,9 @@ private long getTotalCpuTime()
         return TimeUnit.NANOSECONDS.toNanos(totalCpuTime);
     }
 
-    private List<URI> getAllNodes(URI server)
+    private List<URI> getAllNodes(URI server, String user)
     {
-        Request request = prepareGet().setUri(uriBuilderFrom(server).replacePath("/v1/service/presto").build()).build();
+        Request request = prepareGet().setHeader(PrestoHeaders.PRESTO_USER, user).setUri(uriBuilderFrom(server).replacePath("/v1/service/presto").build()).build();
```
Comment (sopel39) [inline presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java:277]: can we use dummy user instead of actual user name? I think any username will do in benchmarks

Comment (Lewuathe) [reply presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java:277]: @sopel39 Can we ignore the `user` name specified by the option `--user`?

Comment (sopel39) [reply presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java:277]: @Lewuathe I think in benchto for a while some dummy name was used and benchmarks still work. However, I think we can keep it as is

File: presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java [hunk 3]
```diff
@@ -95,7 +96,7 @@ public BenchmarkQueryRunner(int warm, int runs, boolean debug, int maxFailures,
         setupSocksProxy(builder, socksProxy);
         this.okHttpClient = builder.build();
 
-        nodes = getAllNodes(requireNonNull(serverUri, "serverUri is null"));
+        nodes = getAllNodes(requireNonNull(serverUri, "serverUri is null"), requireNonNull(user));
```
Comment (sopel39) [inline presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java:99]: make it `requireNonNull(user, "user is null")`

**Comment by sopel39** [comment]
merged, thanks!
