### PR TITLE
Handle the case where a partition column has null value

### LINKED ISSUE #3716: IcebergConnector: Handle `null` partition value
If the partition value is null. 
here if partition column value is null. it fails with exception.

```File hdfs://abc.parquet has no partition data for partitioning column event_dt\```

Place from where this condition is checked:

```
private static Map<Integer, String> getPartitionKeys(FileScanTask scanTask)
```

```
            if (value == null) {
                throw new PrestoException(ICEBERG_INVALID_PARTITION_VALUE, format(
                        "File %s has no partition data for partitioning column %s",
                        scanTask.file().path().toString(),
                        field.name()));
            }
```

If the similar data read from Spark, then its returning proper data, even though there is partition which has `null` value .

### PR DESCRIPTION
**Pull request by Parth-Brahmbhatt**
Fixes #3716

### CODE REVIEW

File: presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java [hunk 1]
```diff
@@ -121,7 +119,7 @@ private ConnectorSplit toIcebergSplit(TupleDomain<IcebergColumnHandle> predicate
         StructLike partition = scanTask.file().partition();
         PartitionSpec spec = scanTask.spec();
         Map<PartitionField, Integer> fieldToIndex = getIdentityPartitions(spec);
-        ImmutableMap.Builder<Integer, String> partitionKeys = ImmutableMap.builder();
+        Map<Integer, String> partitionKeys = new HashMap<>();
```
Comment (lxynov) [inline presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java:122]: nit: can you use ImmutableMap.Builder so that the code style is consistent with Presto codebase?

Comment (electrum) [reply presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java:122]: The Guava Immutable classes can’t contain null values, but HashMap can.

**Comment by electrum** [comment]
Thanks!
