### PR TITLE
Elasticsearch name clash: omit conflicting keys.

### LINKED ISSUE #2965: Elasticsearch name clash
I'm facing following problem with the ElasticSearch connector. 
The data I would like to search has an unfortunate property that it contains key name clashes when comparing them in a case insensitive manner. See below for the ES mappings example:
```
{
  "my_index": {
    "mappings": {
      "default-json-type": {
        "properties": {
          "keyA": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "conflict": {
            "properties": {
              "inner": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "Conflict": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}
```

With the latest presto version, the following query fails:
```
select * from my_index
```
with the following error:
```
Multiple entries with same key: conflict=ElasticsearchColumnHandle{columnName=conflict, columnType=row(text varchar)} and conflict=ElasticsearchColumnHandle{columnName=Conflict, columnType=varchar}
```
This error originates in Guava `ImmutableMap` builder.
Moreover, I cannot even execute queries that explicitly omit the broken columns:
```
select keyA from my_index
```
as same error is thrown.
Unfortunately, the data cannot be fixed at source. Old version of the elasticsearch connector had `elasticsearch.table-description-directory` property that could be used to manually manage aliases, which fields I'm interested in, etc. But it is no longer present with the latest version.

The easiest fix for it is to exclude both conflicting columns from presto metadata. Do you think some more elaborate solution should be applied (like some renaming strategy to keep both, or something else)?

### PR DESCRIPTION
**Pull request by msosnicki**
Fixes #2965

### CODE REVIEW

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 1]
```diff
@@ -69,6 +71,8 @@
     private final ElasticsearchClient client;
     private final String schemaName;
 
+    private final Locale locale = Locale.getDefault();
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: This will make the chosen local sensitive to what the JVM is configured to use. Let's use `Locale.ENGLISH` like we do everywhere else. 

Also, storing it in a field is unnecessary, so just inline it where it's used.

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java [hunk 2]
```diff
@@ -129,9 +133,12 @@ private ConnectorTableMetadata getTableMetadata(String schemaName, String tableN
         result.add(BuiltinColumns.SOURCE.getMetadata());
         result.add(BuiltinColumns.SCORE.getMetadata());
 
+        Map<String, Long> counts = metadata.getSchema().getFields().stream()
+                .collect(Collectors.groupingBy(f -> f.getName().toLowerCase(locale), Collectors.counting()));
```
Comment (martint) [inline presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: Let's format it as follows:
```suggestion
        Map<String, Long> counts = metadata.getSchema()
                .getFields().stream()
                .collect(Collectors.groupingBy(field -> field.getName().toLowerCase(locale), Collectors.counting()));
```

File: presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java (hunk 1 above)
Comment (msosnicki) [reply presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java]: Makes sense, I missed it, `ENGLISH` is used even in the same file :)

**Comment by martint** [comment]
Merge, thanks for your contribution!
