### PR TITLE
Ensure hive table exists when running Hive procedures

### LINKED ISSUE #2746: hive create_empty_partition procedure fails with NPE when table does not exist

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #2746

### CODE REVIEW

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java [hunk 1]
```diff
@@ -1204,6 +1204,15 @@ private void testCreateEmptyBucketedPartition(HiveStorageFormat storageFormat)
         assertFalse(getQueryRunner().tableExists(getSession(), tableName));
     }
 
+    @Test
+    public void testCreateEmptyPartitionOnNonExistingTable()
+    {
+        String tableName = "non_existing_table";
```
Comment (findepi) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java]: inline inside the format string

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java [hunk 2]
```diff
@@ -4904,6 +4913,9 @@ public void testInvalidDropStats()
         assertQueryFails(
                 format("CALL system.drop_stats('%s', '%s', ARRAY[ARRAY['WRONG', 'KEY']])", TPCH_SCHEMA, partitionedTableName),
                 "Partition '.*' not found");
+        assertQueryFails(
+                format("CALL system.drop_stats('%s', '%s', ARRAY[ARRAY['WRONG', 'KEY']])", TPCH_SCHEMA, "non_existing_table"),
```
Comment (findepi) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java]: inline `non_existing_table ` inside the format string, the same way you did in the expected message

**Comment by findepi** [comment]
Merged, thanks!
