### PR TITLE
Fix generated code when ScalarFunction name has special characters

### LINKED ISSUE #1998: Using dot in ScalarFunctions name value cause failures
We are wring a custom functions like `@ScalarFunction(value = "pretradedate", alias = "default.pretradedate")`. When select on `default.pretradedate`, it throws error
```
io.prestosql.spi.PrestoException: line 1:1: Function default.pretradedate not registered

	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:878)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:316)
	at io.prestosql.sql.tree.FunctionCall.accept(FunctionCall.java:110)
	at io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:339)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:276)
	at io.prestosql.sql.ExpressionTestUtils.planExpression(ExpressionTestUtils.java:92)
	at io.prestosql.operator.scalar.FunctionAssertions.createExpression(FunctionAssertions.java:641)
	at io.prestosql.operator.scalar.FunctionAssertions.executeProjectionWithAll(FunctionAssertions.java:480)
	at io.prestosql.operator.scalar.FunctionAssertions.selectUniqueValue(FunctionAssertions.java:295)
	at io.prestosql.operator.scalar.FunctionAssertions.selectSingleValue(FunctionAssertions.java:290)
	at io.prestosql.operator.scalar.FunctionAssertions.assertFunction(FunctionAssertions.java:253)
	at io.prestosql.operator.scalar.AbstractTestFunctions.assertFunction(AbstractTestFunctions.java:91)
	at cn.com.gf.bdp.presto.udf.tradingday.TradeDateFunctionTest.testPretradeDate(TradeDateFunctionTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: io.prestosql.spi.PrestoException: Function default.pretradedate not registered
	at io.prestosql.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:706)
	at io.prestosql.metadata.MetadataManager.lambda$resolveFunction$19(MetadataManager.java:1312)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.prestosql.metadata.MetadataManager.resolveFunction(MetadataManager.java:1312)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:866)
	... 37 more
```
Presto version: 323

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #1998

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/operator/scalar/CustomFunctions.java [hunk 1]
```diff
@@ -45,4 +45,11 @@ public static boolean customIsNullBigint(@SqlNullable @SqlType(StandardTypes.BIG
     {
         return value == null;
     }
+
+    @ScalarFunction(value = "identity.function", alias = "identity&function")
```
Comment (kokosing) [inline presto-main/src/test/java/io/prestosql/operator/scalar/CustomFunctions.java]: what if you declare other method with name `identity%function` with different body? Which one will be called or what kind of error message will be raised?

Comment (Praveen2112) [reply presto-main/src/test/java/io/prestosql/operator/scalar/CustomFunctions.java]: It might throw `Function already registered: `

File: presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java [hunk 2]
```diff
@@ -335,7 +335,7 @@ else if (type == Boolean.class) {
 
     public static BytecodeExpression invoke(Binding binding, String name)
     {
-        return invokeDynamic(BOOTSTRAP_METHOD, ImmutableList.of(binding.getBindingId()), name, binding.getType());
+        return invokeDynamic(BOOTSTRAP_METHOD, ImmutableList.of(binding.getBindingId()), name.replaceAll("[^(A-Za-z0-9_$)]", "_"), binding.getType());
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: Should we escape the name instead to prevent conflicts?

Comment (sopel39) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: I would add a note that `name` here is for formatting purpose only.

How was it failing before this change?

Comment (Praveen2112) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: This is the error we got 
`java.lang.RuntimeException: Error compiling identity.function($operator$CAST(123)): invalid name: identity.function`

The actual reason was 
```
Caused by: java.lang.IllegalArgumentException: invalid name: identity.function
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at io.airlift.bytecode.instruction.InvokeInstruction.checkUnqualifiedName(InvokeInstruction.java:441)
	at io.airlift.bytecode.instruction.InvokeInstruction.<init>(InvokeInstruction.java:319)
```

It looks like bytecode library doesn't support passing name with `.`

Comment (sopel39) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: Ah, so it seems there might be name conflict at byte level. I think it should be escaped then?

Maybe you add tests that confirms the conflict when `replaceAll` produces same name. I guess such functions need to be within same expression.

Comment (Praveen2112) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: IIRC since we use bindingId to resolve the `MethodHandle` for the scalar function the name shouldn't be a problem (even if it sees a similar scalar function name). I have updated the tests cases for the same and it wasn't showing any issues

Comment (sopel39) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: @electrum could you validate reasoning here?

@Praveen2112 I would still use escaping here as just to be safe as it's seem generated bytecode actually uses that method name

Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: At the bytecode level, invokedynamic takes a string as a name and any other arguments the caller wants to pass to the bootstrap function. The name can be anything, but our bytecode library wrapper in airlift is incorrectly, enforcing that it’d be a valid Java identifier. We should fix that constraint there.

Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: I was mistaken. There was some talk a few years ago about relaxing the constraints in the VM regarding how to formulate those identifiers to improve interop with other languages (which is the main reason invokedynamic was introduced in the first place), but the discussion went nowhere.

Comment (sopel39) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: so essentially this `name.replaceAll("[^(A-Za-z0-9_$)]", "_")` is the correct fix?

Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: Yes. If the name was significant, we’d mangle it in a way that was reversible, but we resolve the linkage based on an artificial “binding id”

File: presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java [hunk 3]
```diff
@@ -335,7 +335,8 @@ else if (type == Boolean.class) {
 
     public static BytecodeExpression invoke(Binding binding, String name)
     {
-        return invokeDynamic(BOOTSTRAP_METHOD, ImmutableList.of(binding.getBindingId()), name, binding.getType());
+        //ensure that name doesn't have a special characters
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: space after `//`

Comment (Praveen2112) [reply presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java]: Fixed it
