### PR TITLE
Fix fails query if bucket number exceeds declared bucket size

### LINKED ISSUE #4378: Hive connector silently ignores extra buckets
`BackgroundHiveSplitLoader.getBucketedSplits()` should verify that every bucket number is less than `partitionBucketNumber`. For example, create a table with a bucket count of `4` and then create these files:
```
0000_0
0001_0
0003_0
0004_0
0009_0
```
The files for buckets 4 and 9 are silently skipped. The query should instead fail with `HIVE_INVALID_BUCKET_FILES`.

### PR DESCRIPTION
**Pull request by ArvinZheng**
fix #4378

### CODE REVIEW

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java [hunk 1]
```diff
@@ -636,6 +639,23 @@ private static boolean shouldUseFileSplitsFromInputFormat(InputFormat<?, ?> inpu
...
     }
 
+    @VisibleForTesting
+    static void validateFileBuckets(ListMultimap<Integer, LocatedFileStatus> bucketFiles, int partitionBucketCount, String tableName, String partitionName)
+    {
+        Integer highestBucketNumber = Collections.max(bucketFiles.keySet());
+        // validate the bucket number detected from files, fail the query if the highest bucket number detected from file
+        // exceeds the allowed highest number
+        if (highestBucketNumber >= partitionBucketCount) {
+            throw new PrestoException(HIVE_INVALID_BUCKET_FILES, format(
```
Comment (sopel39) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:649]: nit: each argument in newline

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java [hunk 2]
```diff
@@ -566,6 +569,41 @@ public void testHive2VersionedFullAcidTableFails()
...
+                .isInstanceOfSatisfying(PrestoException.class, e -> assertEquals(HIVE_INVALID_BUCKET_FILES.toErrorCode(), e.getErrorCode()))
+                .hasMessage("Hive table 'tableName' is corrupt. The highest bucket number in the directory (9) is greater than the highest bucket number declared (8) for partition: partitionName");
+
+        boolean noErrors = true;
+        try {
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 10, "tableName", "partitionName");
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 20, "tableName", "partitionName");
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 30, "tableName", "partitionName");
+        }
+        catch (Throwable e) {
```
Comment (sopel39) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:600]: remove catch, throwing an exception will cause test to fail anyway

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 1 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: fixed

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java [hunk 3]
```diff
@@ -566,6 +570,41 @@ public void testHive2VersionedFullAcidTableFails()
...
+                .hasMessage("Hive table 'tableName' is corrupt. The highest bucket number in the directory (9) is greater than the highest bucket number " +
+                        "declared (8) for partition: partitionName");
+
+        try {
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 10, "tableName", "partitionName");
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 20, "tableName", "partitionName");
+            BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 30, "tableName", "partitionName");
+        }
+        catch (Throwable e) {
+            Assert.shouldNeverReachHere();
```
Comment (sopel39) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:604]: static import

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java [hunk 4]
```diff
@@ -636,6 +639,28 @@ private static boolean shouldUseFileSplitsFromInputFormat(InputFormat<?, ?> inpu
...
     }
 
+    @VisibleForTesting
+    static void validateFileBuckets(ListMultimap<Integer, LocatedFileStatus> bucketFiles, int partitionBucketCount, String tableName, String partitionName)
+    {
+        if (bucketFiles.isEmpty()) {
+            return;
+        }
+
+        Integer highestBucketNumber = Collections.max(bucketFiles.keySet());
```
Comment (sopel39) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:649]: static import `max`

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java [hunk 5]
```diff
@@ -636,6 +639,28 @@ private static boolean shouldUseFileSplitsFromInputFormat(InputFormat<?, ?> inpu
...
+        // validate the bucket number detected from files, fail the query if the highest bucket number detected from file
+        // exceeds the allowed highest number
+        if (highestBucketNumber >= partitionBucketCount) {
+            throw new PrestoException(
+                    HIVE_INVALID_BUCKET_FILES,
+                    format("Hive table '%s' is corrupt. The highest bucket number in the directory (%s) is greater than the highest bucket " +
```
Comment (sopel39) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:655]: each arg in newline

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java (hunk 3 above)
Comment (ArvinZheng) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java]: fixed

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 4 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: fixed

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 5 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: reformatted again

**Comment by ArvinZheng** [comment]
@sopel39 thank you very much for your time.

**Comment by electrum** [comment]
The commit message title is too long. Please shorten to something like

> Fail query if there are too many buckets

We follow these guidelines: https://chris.beams.io/posts/git-commit/

When updating the PR, please squash the commits into a single commit (we don't want to merge "fixup" commits).

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java [hunk 6]
```diff
@@ -636,6 +639,27 @@ private static boolean shouldUseFileSplitsFromInputFormat(InputFormat<?, ?> inpu
...
     }
 
+    @VisibleForTesting
+    static void validateFileBuckets(ListMultimap<Integer, LocatedFileStatus> bucketFiles, int partitionBucketCount, String tableName, String partitionName)
+    {
+        if (bucketFiles.isEmpty()) {
+            return;
+        }
+
+        Integer highestBucketNumber = max(bucketFiles.keySet());
```
Comment (electrum) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:649]: This can be declared as `int`

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java [hunk 7]
```diff
@@ -636,6 +639,27 @@ private static boolean shouldUseFileSplitsFromInputFormat(InputFormat<?, ?> inpu
...
+        // validate the bucket number detected from files, fail the query if the highest bucket number detected from file
+        // exceeds the allowed highest number
+        if (highestBucketNumber >= partitionBucketCount) {
+            throw new PrestoException(HIVE_INVALID_BUCKET_FILES, format(
+                    "Hive table '%s' is corrupt. The highest bucket number in the directory (%s) is greater than the highest bucket number " +
+                            "declared (%s) for partition: %s",
+                    tableName,
+                    highestBucketNumber,
+                    partitionBucketCount - 1,
```
Comment (electrum) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:658]: Remove `- 1` after changing error message

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java [hunk 8]
```diff
@@ -566,6 +571,41 @@ public void testHive2VersionedFullAcidTableFails()
...
+    public void testValidateFileBuckets()
+    {
+        ListMultimap<Integer, LocatedFileStatus> bucketFiles = ArrayListMultimap.create();
+        bucketFiles.put(1, null);
+        bucketFiles.put(3, null);
+        bucketFiles.put(4, null);
+        bucketFiles.put(6, null);
+        bucketFiles.put(9, null);
+
+        assertThatThrownBy(() -> BackgroundHiveSplitLoader.validateFileBuckets(bucketFiles, 1, "tableName", "partitionName"))
```
Comment (electrum) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:584]: Static import `validateFileBuckets` for readability

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java (hunk 2 above)
Comment (electrum) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:604]: These are expected to be positive test cases that don't throw. Having try/catch is strange, as any exception will cause a test failure. By this logic, we would need try/catch in every test, as we normally expect that a test will not throw.

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java (hunk 8 above)
Comment (electrum) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:584]: You can do this using
```java
assertPrestoExceptionThrownBy(() -> validateFileBuckets(bucketFiles, 1, "tableName", "partitionName"))
        .hasErrorCode(HIVE_INVALID_BUCKET_FILES)
        .hasMessage(...);

**Comment by ArvinZheng** [comment]
@electrum For sure I will squash all the commits into one and shorten the commit message after all comments are addressed.
But what do you think about
> Fail query if there are invalid buckets

compare to

> Fail query if there are too many buckets

BTW, if you don't have any comments I'll go ahead and squash the commit once I get your response on the commit mesage.

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 6 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:649]: good catch

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java (hunk 2 above)
Comment (ArvinZheng) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:604]: got it, will remove it

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 7 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:658]: I was thinking the same when I was trying to organize the error message, then I chose to make this trade off since I was not able to figure out a better one - how about `Hive table '%s' is corrupt. The highest bucket number in the directory (%s) exceeds the bucket number range defined by the declared bucket count (%s) for partition: %s`

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java (hunk 8 above)
Comment (ArvinZheng) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java:584]: got it

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 7 above)
Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java:658]: one error message example that may look a bit odd, feel free to suggest a better one 
> Hive table 'tableName' is corrupt. The highest bucket number in the directory (9) exceeds the bucket number range defined by the declared bucket count (9) for partition: partitionName

**Comment by electrum** [comment]
@ArvinZheng either one sounds good to me. Apart from the review comments, I don't have anything else. It should be ready to merge after those addressed. Thanks for the quick response.

**Comment by ArvinZheng** [comment]
@electrum addressed all the comments except for the error message, replied you inline, trying to figure out a better sentence, mind taking a look, thanks.

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 7 above)
Comment (electrum) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: I see what you mean. Maybe we could list the range explicitly?

> Hive table 'tableName' is corrupt. The highest bucket number in the directory (9) exceeds the bucket number range (0..8) defined by the declared bucket count (9) for partition: partitionName

**Comment by electrum** [comment]
Thanks!

File: presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java (hunk 7 above)
Comment (electrum) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: I merged the PR since this seems good enough for now. If you want to try adding the range or otherwise improving the error message, feel free to send a follow up PR.

Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: Yup, that's my concern. To show the bucket range I'll need to do calculation on the `partitionBucketCount`, maybe extra a method will have better readability for the code, what do you think?
BTW, thanks for your time on reviewing the code.

Comment (electrum) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: The only calculation is `partitionBucketCount - 1` so I don't think we need a method (the range always starts at zero).

Comment (ArvinZheng) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java]: Yes, my concerns is whether `subtracting 1` from `partitionBucketCount` is easy for people to understand, otherwise i am good to go with `partitionBucketCount - 1` directly.
