### PR TITLE
Validate session catalog in role commands

### LINKED ISSUE #2767: USE fails when in an invalid catalog when a role for that catalog is set
```
$ presto --debug --catalog test
presto> set role admin;
SET ROLE
presto> use tpch.tiny;
Query 20200208_184255_00004_a53s9 failed: Catalog does not exist: test
io.prestosql.spi.PrestoException: Catalog does not exist: test
        at io.prestosql.Session.lambda$beginTransactionId$3(Session.java:332)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.prestosql.Session.beginTransactionId(Session.java:332)
        at io.prestosql.execution.QueryStateMachine.beginWithTicker(QueryStateMachine.java:231)
        at io.prestosql.execution.QueryStateMachine.begin(QueryStateMachine.java:198)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.createDispatchQuery(LocalDispatchQueryFactory.java:98)
        at io.prestosql.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:192)
        at io.prestosql.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:146)
        at io.prestosql.$gen.Presto_null__testversion____20200208_184148_3.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by electrum**
Fixes #2767

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java [hunk 1]
```diff
@@ -87,14 +89,29 @@ public void testSetRole()
         assertSetRole("SET ROLE bar", ImmutableMap.of(CATALOG_NAME, new SelectedRole(SelectedRole.Type.ROLE, Optional.of("bar"))));
     }
 
+    @Test
+    public void testSetRoleInvalidCatalog()
+    {
+        assertPrestoExceptionThrownBy(() -> executeSetRole("invalid", "SET ROLE foo"))
```
Comment (kokosing) [inline presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java]: Can you please add tests for other statements?

Comment (electrum) [reply presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java]: Done
