### PR TITLE
Return varchar type for substr function with char argument

### LINKED ISSUE #3456: Substr to a CHAR(n) column returns padded string
## Problem
When I do substr to a fixed length CHAR(n) column, it returns white-space-padded string. But I think it should return a truncated string without padding.

I've done the same thing in MySQL and it returned a truncated string which I expected for.

## How to reproduce
1. Make a CHAR type column (e.g. CHAR(8)) to a table
2. Insert a row with text (e.g. `abcd1234`)
3. Select it with substr (e.g. `select substr(col1, 1, 4) from T`)

## Expected return
varchar(n) `abcd` (truncated text)

## Actual return
char(n) `abcd     ` (four white spaces padded)

## Presto version
331

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #3456

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java [hunk 1]
```diff
@@ -390,41 +390,41 @@ public void testSubstring()
...
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), 5, 10)", createVarcharType(13), "ratically");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), 5, 50)", createVarcharType(13), "ratically");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), 50, 10)", createVarcharType(13), "");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), -5, 4)", createVarcharType(13), "call");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), -5, 40)", createVarcharType(13), "cally");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), -50, 4)", createVarcharType(13), "");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), 0, 4)", createVarcharType(13), "");
+        assertFunction("SUBSTR(CAST('Quadratically' AS CHAR(13)), 5, 0)", createVarcharType(13), "");
+
+        assertFunction("SUBSTR(CAST('abc def' AS CHAR(7)), 1, 4)", createVarcharType(7), "abc ");
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java:409]: do we have a test ensuring trailing space is preserved?
like
```
assertFunction("SUBSTR(CAST('keep trailing' AS CHAR(14)), 1, 14)", createVarcharType(14), "keep trailing ");
```

Comment (ebyhr) [reply presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java:409]: Thanks, I was missing the case. Updated.
