### PR TITLE
Use listCollections command to find MongoDB view

### LINKED ISSUE #3348: Mongo connector throws "not authorized on db to execute command" when Presto cannot access system.views
If Presto service user doesn't have permission to access `system.views`, every access to a Mongo table fails with `not authorized on db to execute command` error from Mongo.

https://github.com/prestosql/presto/blob/3366910fb95681be013cf7123806fcfda3a39775/presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java#L608-L613

Using [type](https://docs.mongodb.com/manual/reference/command/listCollections/#output) field from listCollections' result might resolve it.

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #3348

Reference https://docs.mongodb.com/manual/reference/command/listCollections/

### CODE REVIEW

File: presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java [hunk 1]
```diff
@@ -607,8 +608,16 @@ else if (value instanceof Document) {
 
     private boolean isView(SchemaTableName tableName)
     {
-        MongoCollection views = client.getDatabase(tableName.getSchemaName()).getCollection("system.views");
-        Object view = views.find(new Document("_id", tableName.toString())).first();
-        return view != null;
+        Document listCollectionsCommand = new Document(ImmutableMap.of(
```
Comment (martint) [inline presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java:611]: For multiple entries, using `ImmutableMap.builder()` is clearer:

```
ImmutableMap.builder()
    .put(...)
    .put(...)
    .put(...)
    .build()
```

**Comment by ebyhr** [comment]
I think we can test it by preparing a weak user in MongoServer class. (I'm looking into that)
