### PR TITLE
Fix querying information schema with empty name as predicate

### LINKED ISSUE #2523: Error when querying information schema with empty table_name predicate
```
select * from "hive"."information_schema"."tables" WHERE table_schema='tpch' AND table_name=''
```

Is causing:
```
java.lang.IllegalArgumentException: tableName is empty
	at io.prestosql.spi.connector.SchemaUtil.checkNotEmpty(SchemaUtil.java:28)
	at io.prestosql.spi.connector.SchemaTableName.<init>(SchemaTableName.java:33)
	at io.prestosql.metadata.QualifiedObjectName.asSchemaTableName(QualifiedObjectName.java:75)
	at io.prestosql.metadata.CatalogMetadata.getConnectorId(CatalogMetadata.java:115)
	at io.prestosql.metadata.MetadataManager.getTableHandle(MetadataManager.java:285)
	at io.prestosql.metadata.MetadataManager.listTables(MetadataManager.java:507)
	at io.prestosql.metadata.MetadataListing.listTables(MetadataListing.java:64)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addTablesRecords(InformationSchemaPageSource.java:268)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:210)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:173)
	at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:362)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.access$000(WorkProcessorUtils.java:37)
	at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:148)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_null__testversion____20200116_131217_4.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #2523

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java [hunk 1]
```diff
@@ -217,6 +218,36 @@ public void testInformationSchemaPredicatePushdownOnCatalogWiseTables()
         assertFalse(result.isPresent());
     }
 
+    @Test
+    public void testInformationSchemaPredicatePushdownForEmptyNames()
```
Comment (kokosing) [inline presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java]: Can you please also add a test to `TestInformationSchemaConnector` where you run actual query and verify the result?

File: presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java [hunk 2]
```diff
@@ -217,6 +218,36 @@ public void testInformationSchemaPredicatePushdownOnCatalogWiseTables()
...
+        tableHandle = (InformationSchemaTableHandle)
+                metadata.getTableHandle(session, new SchemaTableName("information_schema", "tables"));
+        constraint = new Constraint(TupleDomain.fromFixedValues(
+                ImmutableMap.of(
+                        new InformationSchemaColumnHandle("table_schema"), new NullableValue(VARCHAR, Slices.utf8Slice("")))));
+        tableHandle = metadata.applyFilter(session, tableHandle, constraint)
+                .map(ConstraintApplicationResult::getHandle)
+                .map(InformationSchemaTableHandle.class::cast)
+                .orElseThrow(AssertionError::new);
+        assertTrue(tableHandle.getPrefixes().isEmpty());
```
Comment (kokosing) [inline presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java]: can you please extract an assertion method and call it twice: `assertApplyFiterReturnsEmptyPrefixes(             ImmutableMap.of(
                        new InformationSchemaColumnHandle("table_schema"), new NullableValue(VARCHAR, Slices.utf8Slice(""))));`? and same for `table_name`

File: presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java [hunk 3]
```diff
@@ -311,6 +311,13 @@ private boolean isColumnsEnumeratingTable(InformationSchemaTable table)
     }
 
     private <T> Optional<Set<String>> filterString(TupleDomain<T> constraint, T column)
+    {
+        return generateFilterFromTupleDomain(constraint, column)
+                .map(filteredString -> filteredString.stream()
+                        .filter(value -> !value.isEmpty()).collect(toImmutableSet()));
```
Comment (kokosing) [inline presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java]: move collect to new line

Comment (kokosing) [inline presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java]: This `.filter(value -> !value.isEmpty())` can be only called for columns that we known that cannot have empty values (catalog, schema, table, column) however `filterString` suggests it is generic. Maybe rename or `filterEmptyValues(filterString(...))`? So it would be used in place where column is known.

**Comment by Praveen2112** [comment]
@kokosing Thanks for your insight. Have applied the comments

File: presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java [hunk 4]
```diff
@@ -310,6 +310,14 @@ private boolean isColumnsEnumeratingTable(InformationSchemaTable table)
                 .map(schema -> new QualifiedTablePrefix(catalogName, schema));
     }
 
+    private <T> Optional<Set<String>> filterEmptyValues(TupleDomain<T> constraint, T column)
```
Comment (kokosing) [inline presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java]: I was thinking of method like `String<Set> removeEmptyValues(Set<String values)`. Then you would use it like `filterString(constraint, column).map(this::removeEmptyValues)`

Comment (Praveen2112) [reply presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java]: Updated

File: presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java [hunk 5]
```diff
@@ -347,6 +347,13 @@ private boolean isColumnsEnumeratingTable(InformationSchemaTable table)
         return Optional.empty();
     }
 
+    private Set<String> removeEmptyValues(Set<String> values)
```
Comment (kokosing) [inline presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java]: static
this method is very much of utility kind, so I would define it at the very bottom of this class

**Comment by kokosing** [comment]
Merged, thanks!
