### PR TITLE
Fix SHOW CREATE TABLE if row type column contains special character

### LINKED ISSUE #3380: SHOW CREATE TABLE fails if row type column contains special character
Steps to reproduce
```sql
presto> create table memory.default.test as select CAST(ROW(1, 2e0) AS ROW("$x" BIGINT, y DOUBLE)) as c1;
CREATE TABLE: 1 row

presto> show create table memory.default.test;
Query 20200408_021754_00021_rp7e3 failed: value contains illegal characters: $x

presto> select * from memory.default.test;
      c1
---------------
 {$x=1, y=2.0}
(1 row)
```

```
java.lang.IllegalArgumentException: value contains illegal characters: $x
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at io.prestosql.sql.tree.Identifier.<init>(Identifier.java:56)
	at io.prestosql.sql.tree.Identifier.<init>(Identifier.java:41)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.lambda$null$2(TypeSignatureTranslator.java:189)
	at java.util.Optional.map(Optional.java:215)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.lambda$toDataType$3(TypeSignatureTranslator.java:189)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.toDataType(TypeSignatureTranslator.java:191)
	at io.prestosql.sql.analyzer.TypeSignatureTranslator.toSqlType(TypeSignatureTranslator.java:63)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.lambda$visitShowCreate$8(ShowQueriesRewrite.java:472)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:474)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:155)
	at io.prestosql.sql.tree.ShowCreate.accept(ShowCreate.java:67)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:152)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:57)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:80)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:220)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:179)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:96)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:730)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_null__testversion____20200408_021428_4.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #3380

### CODE REVIEW

**Comment by findepi** [comment]
Why was `SHOW CREATE TABLE` more affected than statements?

**Comment by findepi** [comment]
@Praveen2112 doe this also fix SHOW CREATE TABLE when row has field named after SQL keyword?

```
CREATE TABLE t(x row("catalog" varchar, "schema" varchar, "table" varchar));

SHOW CREATE TABLE t;
```

can you add integration test for SHOW CREATE TABLE for both cases (dollar, keyword)?

**Comment by Praveen2112** [comment]
> does this also fix SHOW CREATE TABLE when row has field named after SQL keyword?

That was already fixed

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java [hunk 1]
```diff
@@ -3233,6 +3233,24 @@ public void testShowCreateTable()
         assertUpdate(createTableSql);
         actualResult = computeActual("SHOW CREATE TABLE \"test_show_create_table'2\"");
         assertEquals(getOnlyElement(actualResult.getOnlyColumnAsSet()), createTableSql);
+
+        createTableSql = format("" +
+                        "CREATE TABLE %s.%s.%s (\n" +
+                        "   c1 ROW(\"$a\" bigint, \"catalog\" varchar)\n)\n",
```
Comment (findepi) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java:3239]: unnecessary \n, unless you reuse `createTableSql` in the assertion below

add more keywords like `table` or `select

File: presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java [hunk 2]
```diff
@@ -3233,6 +3233,24 @@ public void testShowCreateTable()
...
+        assertThat(computeActual("SHOW CREATE TABLE test_show_create_table_with_special_characters").getOnlyValue())
+                .isEqualTo(format("" +
+                                "CREATE TABLE %s.%s.%s (\n" +
+                                "   c1 ROW(\"$a\" bigint, catalog varchar)\n)\n",
+                        getSession().getCatalog().get(),
+                        getSession().getSchema().get(),
+                        "test_show_create_table_with_special_characters") +
+                        "WITH (\n" +
+                        "   format = 'ORC'\n" +
+                        ")");
```
Comment (findepi) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java:3253]: you should be able to use `createTableSql` here
you cannot because `catalog` is no longer delimited

but, that also means  user cannot take `SHOW CREATE TABLE` output and use it to create the table.
Since this is _the purpose_ of the SHOW CREATE TABLE query, it's  a no-go to me.

Comment (findepi) [reply presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java]: logged https://github.com/prestosql/presto/issues/3584
