### PR TITLE
Display proper view name for show create queries

### LINKED ISSUE #433: Show Create View generates invalid view name.
When the user provide fully qualified view name in show create queries, generated result will output the wrong view name. For example

    show create view hive.a.b 

will result in

    create view b.a.hive

This is due to the following lines, which assume table name is `parts[0]`, while in fact it can be `parts[1]` or `parts[2]` (the last value) depending on the user's provided view name.

https://github.com/prestosql/presto/blob/b7aa1efa45fc87be03ddb24377b44415aa0d8e22/presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java#L434

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #433. When the query has a fully qualified view name for show create, generated result displays the name in a wrong order. This patch ensures that view name is shown in proper order. Test is also updated for the same.

### CODE REVIEW

**Comment by Praveen2112** [comment]
@martint Can you review this ?

File: presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java [hunk 1]
```diff
@@ -749,6 +749,10 @@ public void testViewMetadata()
 
         assertEquals(getOnlyElement(actual.getOnlyColumnAsSet()), expectedSql);
 
+        actual = computeActual(format("SHOW CREATE VIEW %s.%s.meta_test_view", getSession().getCatalog().get(), getSession().getSchema().get()));
+
+        assertEquals(getOnlyElement(actual.getOnlyColumnAsSet()), expected);
```
Comment (martint) [inline presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java]: I think this should be `expectedSql`

Comment (Praveen2112) [reply presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java]: Yes. Changed it.
