### PR TITLE
getTableDefaultLocation should not called if external_location present

### LINKED ISSUE #4069: Presto trying to access default table location even when external_location is provided
From https://prestosql.slack.com/archives/CGB0QHWSW/p1592389129168400

Reproduced on Presto 334.

1. Create a schema with default location pointing to some non-existent/inaccessible node. (In my case this was due to a pre-existing schema on AWS Glue).

```sql
CREATE SCHEMA awsdatacatalog.express_dwh WITH (
    location = 'hdfs://some-inaccessible-node:8020/user/hive/warehouse/express_dwh.db'
)
```

2. Run a CTAS for an external table

```sql
CREATE TABLE new_table WITH (
    format = 'PARQUET',
    external_location = 's3://some-bucket-that-exists/new_table/',
    partitioned_by=ARRAY['ad']
) AS SELECT * FROM some.table
```

This causes an `io.prestosql.spi.PrestoException: Failed checking path: hdfs://some-inaccessible-node:8020/user/hive/warehouse/express_dwh.db` with stack trace:

```log
io.prestosql.spi.PrestoException: Failed checking path: hdfs://ip-some-ip-not-in-cluster:8020/user/hive/warehouse/express_dwh.db
	at io.prestosql.plugin.hive.util.HiveWriteUtils.pathExists(HiveWriteUtils.java:486)
	at io.prestosql.plugin.hive.util.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:469)
	at io.prestosql.plugin.hive.util.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:457)
	at io.prestosql.plugin.hive.HiveLocationService.forNewTable(HiveLocationService.java:58)
	at io.prestosql.plugin.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:1271)
	at io.prestosql.plugin.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:255)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:366)
	at io.prestosql.metadata.MetadataManager.beginCreateTable(MetadataManager.java:777)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:179)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:142)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at io.prestosql.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:198)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:187)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:182)
	at io.prestosql.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:393)
	at io.prestosql.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:381)
	at io.prestosql.execution.SqlQueryExecution.start(SqlQueryExecution.java:336)
	at io.prestosql.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.prestosql.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:132)
	at io.prestosql.$gen.Presto_334____20200617_013735_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hadoop.net.ConnectTimeoutException: Call From ip-master/ip-master to ip-some-ip-not-in-cluster:8020 failed on socket timeout exception: org.apache.hadoop.net.ConnectTimeoutException: 500 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=ip-some-ip-not-in-cluster:8020]; For more details see:  http://wiki.apache.org/hadoop/SocketTimeout
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:831)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:775)
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1515)
	at org.apache.hadoop.ipc.Client.call(Client.java:1457)
	at org.apache.hadoop.ipc.Client.call(Client.java:1367)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy294.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:903)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy295.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1665)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1582)
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1579)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1594)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:454)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1683)
	at io.prestosql.plugin.hive.util.HiveWriteUtils.pathExists(HiveWriteUtils.java:483)
	... 40 more
Caused by: org.apache.hadoop.net.ConnectTimeoutException: 500 millis timeout while waiting for channel to be ready for connect. ch : java.nio.channels.SocketChannel[connection-pending remote=ip-172-20-28-16.ec2.internal/172.20.28.16:8020]
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:534)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:690)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:794)
	at org.apache.hadoop.ipc.Client$Connection.access$3700(Client.java:411)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1572)
	at org.apache.hadoop.ipc.Client.call(Client.java:1403)
	... 63 more
```

**NOTE: CTAS works properly in a schema with the proper `location` set**

### PR DESCRIPTION
**Pull request by hashhar**
In
https://github.com/prestosql/presto/commit/66c360963e690a13b5a526060d7faac2110279ef
CTAS was fixed to use the external_location if provided but due to the
way Optional.orElse() works it still ended up calling
getTableDefaultLocation() which will throw errors if the location
defined in the schema cannot be accessed. This can be fixed by the user
by fixing the location defined in the schema - but Hive doesn't allow
that. So the other option is to not check the location defined in the
schema until absolutely needed.

Fixes #4069.

### CODE REVIEW

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public HiveLocationService(HdfsEnvironment hdfsEnvironment)
     public LocationHandle forNewTable(SemiTransactionalHiveMetastore metastore, ConnectorSession session, String schemaName, String tableName, Optional<Path> externalLocation)
     {
         HdfsContext context = new HdfsContext(session, schemaName, tableName);
-        Path targetPath = externalLocation.orElse(getTableDefaultLocation(context, metastore, hdfsEnvironment, schemaName, tableName));
```
Comment (findepi) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java:58]: sigh. i wish `orElse` had longer name, so that it would be simply more convenient to call `orElseGet`.

I guess you can find many places like that in the codebase.

Comment (hashhar) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java:58]: I'll add tests to exercise this check later - meanwhile you can ignore this PR. So true about Optional, I myself was surprised seeing this behaviour.

**Comment by hashhar** [comment]
@findepi I'm unable to figure out a good test for this change.

An integration test would look like:
1. Create a new schema with a location set.
2. Somehow make the location inaccessible for the duration of the test.
3. CTAS with external_location set should not fail.

I can't figure out a way to do step 2. Any pointers will be appreciated. FYI I'm looking to add the test in `TestHiveCreateExternalTable`.

**Comment by yunrougong** [comment]
> @findepi I'm unable to figure out a good test for this change.
> 
> An integration test would look like:
> 
> 1. Create a new schema with a location set.
> 2. Somehow make the location inaccessible for the duration of the test.
> 3. CTAS with external_location set should not fail.
> 
> I can't figure out a way to do step 2. Any pointers will be appreciated. FYI I'm looking to add the test in `TestHiveCreateExternalTable`.
> 
> **EDIT: Simply creating a schema with a fictional location doesn't work since we check for the existence before schema is created.**

Not sure if this helps create a test case. 
I'm running into a situation where my create schema is empty
`create schema test_schema`
and the create table as external location returns error location for test_schema is not set.

**Comment by hashhar** [comment]
Thanks @yunrougong. I'll try that out too.

If that doesn't work, I'll write a Product Test which uses the Thrift metastore service rather than the FileMetastore we use for tests.

**Comment by hashhar** [comment]
@findepi A test is also added now but it will fail for now because:

1. The Hive product tests (at least `TestExternalHiveTable`) have `hive.non-managed-table-writes-enabled` set to `false` which causes the CTAS to fail.
2. Enabling that config causes rest of the tests in that file to fail.

Where should I place the new test? There is `TestExternalHiveTable` (but it doesn't CREATE an external table) and there is also `TestCreateDropSchema` which creates a schema, a table and then drops both.

**NOTE: While testing this I saw something concerning. A plain `CREATE TABLE` with external_location succeeds. Only CTAS is failing. I saw that both `beginCreateTable` and `createTable` in `HiveMetadata` are eventually calling the offending method in `HiveLocationService` so I'm unable to make sense of this.**

```
presto:express_dwh> create table ctas_nonexistent_schema_test (str varchar) with (external_location='s3://some/location');
CREATE TABLE
presto:express_dwh> insert into ctas_nonexistent_schema_test values ('should not work');
INSERT: 1 row
0.54 [0 rows, 0B] [0 rows/s, 0B/s]
presto:express_dwh> create table ctas_nonexistent_schema_test2 with (external_location='s3://some/location2') as select * from tpch.tiny.nation;
Query 20200711_184342_00814_5y42j failed: Failed checking path: hdfs://ip-172-20-28-16.ec2.internal:8020/user/hive/warehouse/express_dwh.db
```

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java [hunk 2]
```diff
@@ -46,6 +53,27 @@ public Requirement getRequirements(Configuration configuration)
                 mutableTable(NATION_PARTITIONED_BY_BIGINT_REGIONKEY));
     }
 
+    @Test
+    public void testCreateExternalTableWithInaccessibleSchemaLocation()
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:57]: this fails on CI

```
2020-07-11T18:47:14.9602286Z tests               | io.prestosql.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20200711_184714_00781_asknk): Writes to non-managed Hive tables is disabled
```

sadly, we would need a separate environment with different hive.properties unlocking this... 

as this requires quite a few steps, and I am not sure of how much added value this actually brings, 
i would be OK taking a step back and not doing a test at all cc @kokosing @electrum 
(sorry, i didnt foreseen this earlier)

if we want to go with a test, i can provide necessary guidance.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java [hunk 3]
```diff
@@ -46,6 +53,27 @@ public Requirement getRequirements(Configuration configuration)
...
+            throws IOException
+    {
+        File tempDir = createTempDir();
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:60]: The temp dir is local in the tests' containers, so it can as well not exist at all, am i right?

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java (hunk 2 above)
Comment (hashhar) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:57]: I think a test would be good and can be done if does not complicate the CI too much and is as simple as adding a new pt-config.

Or we can add a *hidden* session property (there's already more of those - like query_max_stages) to bypass for the test if we absolutely need a test.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java (hunk 3 above)
Comment (hashhar) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:60]: Hmmmm, good point, not sure if this step is even needed. I'll need to verify though.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java (hunk 2 above)
Comment (findepi) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:57]: > ~Or we can add a _hidden_ session property (there's already more of those - like query_max_stages) to bypass for the test if we absolutely need a test.~

I guess you figured this could be a security issue.

> I think a test would be good and can be done if does not complicate the CI too much and is as simple as adding a new pt-config.

not a pt config.
rather, a new environment, similar to `singlenode` but allowing to create/write external tables
(`singlenode-with-writes-to-external` ?)

Then you'd add an invocation of `test run` to a suite 1/2/3 or 5.

Comment (hashhar) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java:57]: Yes, I was more hinting about cleaning up those other **hidden** session properties sometime since after discovering them I had to add controls in place to disallow setting those for non-admin users.

Thanks @findepi for guiding about the test. Since this will be a completely new test environment running essentially 1 test, would this envrionment be useful for other tests as well? Otherwise I also think it's a slight overkill for this change.

**Comment by hashhar** [comment]
Continuing conversation from https://github.com/prestosql/presto/pull/4279#discussion_r456376262.

Yes, I was more hinting about cleaning up those other **hidden** session properties sometime since after discovering them I had to add controls in place to disallow setting those for non-admin users.

> rather, a new environment, similar to singlenode but allowing to create/write external tables
(singlenode-with-writes-to-external ?)
>
> Then you'd add an invocation of test run to a suite 1/2/3 or 5.

Thanks @findepi for guiding about the test. Since this will be a completely new test environment running essentially 1 test, would this envrionment be useful for other tests as well? Otherwise I also think it's a slight overkill for this change.

**Comment by findepi** [comment]
> Since this will be a completely new test environment running essentially 1 test, would this envrionment be useful for other tests as well? 

Many other tests  _could_ be run on such environment, but that wouldn't really increase test coverage.
So today -- no.

> Otherwise I also think it's a slight overkill for this change.

Thanks for taking the time to explore all these options. I am OK not having a test here.

**Comment by hashhar** [comment]
@findepi The tests are there now - but as you said it looks like too much code for too little benefit - at least today.

Do let me know if we want to keep them or drop them.

**Comment by kokosing** [comment]
> Do let me know if we want to keep them or drop them.

Do you think having something like: https://github.com/prestosql/presto/issues/4510 would be help here. Notice that setup time would still be noticeable as HMS and HDFS takes time to start, but at least you would be able to run it from IDE and it would be easier to maintain such single use case environments.

If so, I would leave these tests and then refactor them.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+    {
+        hdfsClient.delete(warehouseDirectory + "/TestHiveCreateExternalTable");
+    }
+
+    @Override
+    public Requirement getRequirements(Configuration configuration)
+    {
+        return compose(
+                mutableTable(NATION));
+    }
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java:63]: redundant?

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+public class TestHiveCreateExternalTable
+        extends ProductTest
+        implements RequirementsProvider
+{
+    @Inject
+    private HdfsClient hdfsClient;
+
+    @Inject
+    @Named("databases.hive.warehouse_directory_path")
+    private String warehouseDirectory;
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java:43]: I would like to remove warehouse_directory_path.
Here, it's not needed. You can create a directory in (HDFS's) /tmp

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+            throws Exception
+    {
+        hdfsClient.createDirectory(warehouseDirectory + "/TestHiveCreateExternalTable");
+    }
+
+    @AfterTestWithContext
+    public void cleanup()
+    {
+        hdfsClient.delete(warehouseDirectory + "/TestHiveCreateExternalTable");
+    }
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java:56]: Use a shorter (not nested) path for `tableLocation` in the test code
and this will let you remove setup and cleanup from here

(even if you leave a table directory behind, it's not a problem)

**Comment by hashhar** [comment]
@findepi @kokosing Pushed a simplified test setup as suggested (thanks @kokosing) by adding a new Hive catalog with writes to external tables enabled and using that catalog in the test.

I still kept the test class completely separate so that any future related tests can be added here after renaming the class to something more generic.

I think this is ready for a final review now.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java (hunk 6 above)
Comment (hashhar) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java]: Done.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java (hunk 5 above)
Comment (hashhar) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java]: Done.

File: presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeWithWritesToExternal.java [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+    {
+        super(ImmutableList.of(standard, hadoop));
+        this.dockerFiles = requireNonNull(dockerFiles, "dockerFiles is null");
+    }
+
+    @Override
+    protected void extendEnvironment(Environment.Builder builder)
+    {
+        builder.configureContainer("presto-master", container -> container
+                .withCopyFileToContainer(forHostPath(dockerFiles.getDockerFilesHostPath("conf/environment/singlenode-with-writes-to-external/hive.properties")), CONTAINER_PRESTO_HIVE_PROPERTIES));
```
[the remark this answers is not in the document]
Comment (hashhar) [reply presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeWithWritesToExternal.java]: Done. This simplified the tests a lot. Thanks for suggesting.

**Comment by findepi** [comment]
@hashhar can you please squash commits into one?

**Comment by hashhar** [comment]
@findepi Unrelated test failures - one in presto-thrift

```
2020-07-22T05:13:06.3843522Z [ERROR]   TestThriftDistributedQueries>AbstractTestQueries.testCorrelatedNonAggregationScalarSubqueries:1166->AbstractTestQueryFramework.assertQueryFails:221 Expected query to fail: SELECT (SELECT 2 FROM (VALUES 3, 4) WHERE a = 1) FROM (VALUES 1) t(a)
```

And other is the flaky test `io.prestosql.tests.hive.TestCsv.testCreatePartitionedCsvTableAsWithCustomParamters` with `Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hive/14fbe19f-e6f5-4372-9a80-2655c4445cf1/suppkey=15/20200722_051013_00439_nakgd_16892082-b582-483a-943c-d408ca35fac8.gz could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation.`

**Comment by findepi** [comment]
Merged, thanks!
