### PR TITLE
Quote column name in Phoenix CREATE TABLE statement

### LINKED ISSUE #3466: Lack of column names quoting in Phoenix connector's underlying queries
```
CREATE TABLE t("column-with-hyphen" varchar);

SELECT "column-with-hyphen" FROM t

2020-04-17T11:12:45.7820921Z Caused by: org.apache.phoenix.exception.PhoenixParserException: ERROR 601 (42P00): Syntax error. Encountered "-" at line 1, column 110.
2020-04-17T11:12:45.7824069Z 	at org.apache.phoenix.exception.PhoenixParserException.newException(PhoenixParserException.java:33)
2020-04-17T11:12:45.7826666Z 	at org.apache.phoenix.parse.SQLParser.parseStatement(SQLParser.java:111)
2020-04-17T11:12:45.7829968Z 	at org.apache.phoenix.jdbc.PhoenixStatement$PhoenixStatementParser.parseStatement(PhoenixStatement.java:1644)
2020-04-17T11:12:45.7832746Z 	at org.apache.phoenix.jdbc.PhoenixStatement.parseStatement(PhoenixStatement.java:1727)
2020-04-17T11:12:45.7835428Z 	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1819)
2020-04-17T11:12:45.7837960Z 	at io.prestosql.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:824)
2020-04-17T11:12:45.7839196Z 	... 16 more
2020-04-17T11:12:45.7841684Z Caused by: org.apache.phoenix.shaded.org.antlr.runtime.NoViableAltException
2020-04-17T11:12:45.7844612Z 	at org.apache.phoenix.parse.PhoenixSQLParser.column_name(PhoenixSQLParser.java:2966)
2020-04-17T11:12:45.7847892Z 	at org.apache.phoenix.parse.PhoenixSQLParser.column_def(PhoenixSQLParser.java:4458)
2020-04-17T11:12:45.7850839Z 	at org.apache.phoenix.parse.PhoenixSQLParser.column_defs(PhoenixSQLParser.java:4404)
2020-04-17T11:12:45.7884303Z 	at org.apache.phoenix.parse.PhoenixSQLParser.create_table_node(PhoenixSQLParser.java:1236)
2020-04-17T11:12:45.7884460Z 	at org.apache.phoenix.parse.PhoenixSQLParser.oneStatement(PhoenixSQLParser.java:868)
2020-04-17T11:12:45.7884736Z 	at org.apache.phoenix.parse.PhoenixSQLParser.statement(PhoenixSQLParser.java:524)
2020-04-17T11:12:45.7884883Z 	at org.apache.phoenix.parse.SQLParser.parseStatement(SQLParser.java:108)
2020-04-17T11:12:45.7884995Z 	... 20 more
```

### PR DESCRIPTION
**Pull request by ebyhr**
Related to #3466

### CODE REVIEW

File: presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java [hunk 1]
```diff
@@ -136,8 +137,13 @@ public void testCreateSchema()
     @Override
     public void testColumnName(String columnName)
     {
-        // TODO (https://github.com/prestosql/presto/issues/3466) Phoenix generally lacks quoting in underlying queries
-        throw new SkipException("TODO");
+        if (columnName.equals("a\"quote")) {
+            assertThatThrownBy(() -> super.testColumnName(columnName))
+                    .hasMessageContaining("Illegal data. Unsupported sql type: QUOTE");
```
Comment (findepi) [inline presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java:142]: That's incorrect error message. We didn't ask to create a column of _type_ `quote`.

This is because `getEscapedArgument` doesn't support escaping `"` within the name.
If Phoenix does not support this, we need to filter this out on our side.

Then, the correct way to exclude this test case would be like here
https://github.com/prestosql/presto/blob/329a48592ecb6c628712ef3648f2e8da7eb33d38/presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java#L123-L127

Comment (ebyhr) [reply presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java]: @findepi Replaced with `isColumnNameRejected`. As far as I confirmed, we cannot use double-quotation for column name.

Comment (findepi) [reply presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java]: @ebyhr thanks!

please make sure the column name is cleanly rejected at some point, so that user knows this is illegal column _name_, not something else.

eg `io.prestosql.plugin.mysql.TestMySqlDistributedQueries#isColumnNameRejected` verifies the actual exception message contains "Incorrect column name"

File: presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java [hunk 2]
```diff
@@ -351,7 +351,7 @@ private JdbcOutputTableHandle createTable(ConnectorSession session, ConnectorTab
                     typeStatement += " not null";
                     pkNames.add(columnName);
                 }
-                columnList.add(format("%s %s", columnName, typeStatement));
+                columnList.add(format("%s %s", getEscapedArgument(columnName), typeStatement));
```
Comment (findepi) [inline presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java:354]: @vincentpoon should we go thru `toMetadataCasing` here before calling `getEscapedArgument`?

File: presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java [hunk 3]
```diff
@@ -134,10 +134,9 @@ public void testCreateSchema()
     }
 
     @Override
-    public void testColumnName(String columnName)
+    protected boolean isColumnNameRejected(Exception exception, String columnName, boolean delimited)
     {
-        // TODO (https://github.com/prestosql/presto/issues/3466) Phoenix generally lacks quoting in underlying queries
-        throw new SkipException("TODO");
+        return columnName.equals("a\"quote");
```
Comment (findepi) [inline presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java:139]: Leave some TODO comment still.
Currently the `"` in column name leads to SQL injection.
Use of `a"quote` column should produce a reasonable exception message like "Invalid column name" or "Column name cannot contain a quotation sign".  Then, here you should verify the actual `exception` message.

File: presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java (hunk 2 above)
Comment (vincentpoon) [reply presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java:354]: Hmm this code doesn't look right to me (I think it was from another PR I based my original one off of).  Firstly, `connection.getMetaData().storesUpperCaseIdentifiers()` would always return true, so the method `toMetadataCasing` isn't really needed.

Phoenix uppercases identifiers if they aren't quoted.
If they are quoted, then it's case sensitive.

Is there a way for us to tell in Presto whether the user quoted the identifier or not?  Because it seems we should base the uppercase decision off that.

Comment (findepi) [reply presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java:354]: > Is there a way for us to tell in Presto whether the user quoted the identifier or not? Because it seems we should base the uppercase decision off that.

not yet,  working on that -- https://github.com/prestosql/presto/issues/17
