### PR TITLE
Fix duplicate field IDs when creating Iceberg tables

### LINKED ISSUE #1275: Duplicate field IDs when creating an Iceberg table
The following query fails
```
CREATE TABLE iceberg.u_xinlin.exp (
    order_id int,
    user row(user_id int, user_name varchar),
    price double,
    date varchar
)
WITH (partitioning = array['date']);
```
because of duplicate field IDs in an Iceberg `Schema` instance.

https://github.com/prestosql/presto/blob/bc5590c233b240aa531e825efa6cd9876234e7c0/presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java#L277
The `schema` here may have duplicate field IDs because `TypeConveter::toIcebergType` doesn't keep information about a global "next ID".

This should be fine in terms of `TableMetadata::newTableMetadata` refreshes field IDs. But it causes a problem when parsing partition fields (`PartitionFields::parsePartitionFields`).

We can either
1. call `TypeUtil::assignFreshIds` in Iceberg to refresh field IDs before passing it to `PartitionFields::parsePartitionFields`
2. change logic in `TypeConveter::toIcebergType` so that a global "next ID" is used.

@Parth-Brahmbhatt WDYT?

### PR DESCRIPTION
**Pull request by linxingyuan1102**
This fixes #1275 

cc: @Parth-Brahmbhatt , @electrum

### CODE REVIEW

File: presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java [hunk 1]
```diff
@@ -275,8 +277,10 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
         String tableName = schemaTableName.getTableName();
 
         Schema schema = new Schema(toIceberg(tableMetadata.getColumns()));
+        AtomicInteger lastFieldId = new AtomicInteger(0);
```
Comment (electrum) [inline presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java]: We’d normally call this “nextFieldId” (and use get and increment).

**Comment by electrum** [comment]
Can you add a test that fails without this change?

**Comment by linxingyuan1102** [comment]
> Can you add a test that fails without this change?

Sure, I've done that.

File: presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java [hunk 2]
```diff
@@ -275,8 +277,10 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
         String tableName = schemaTableName.getTableName();
 
         Schema schema = new Schema(toIceberg(tableMetadata.getColumns()));
+        AtomicInteger nextFieldId = new AtomicInteger(0);
```
Comment (electrum) [inline presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java]: Is it ok to start fields at `0`, or do they need to start with `1`?

File: presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java [hunk 3]
```diff
@@ -275,8 +277,10 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
         String tableName = schemaTableName.getTableName();
 
         Schema schema = new Schema(toIceberg(tableMetadata.getColumns()));
```
Comment (electrum) [inline presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java]: Let's change `toIceberg` to return `Schema` and move this logic inside there. This will avoid any future callers of this method from having the same problem.

File: presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java (hunk 2 above)
Comment (linxingyuan1102) [reply presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java]: I think it's ok because Iceberg will reassign field IDs anyway. But let's make it to `1` to be consistent with Iceberg's reassigning work.
