### PR TITLE
Fix allow using aggregations in format()

### LINKED ISSUE #3829: "Compiler failed" when aggregation is used as an argument to format()
`format` function was added in `315` but it doesn't support aggregations in the expression (and the doc doesn't mention aggregation is not supported, maybe we should consider adding this to the doc for now).

```
select format('%.6f', sum(fees / 1e6)) from core.rollup where logdate = '2020-05-01'
```

I ran above  query in `317` and got 
```
sum(double):double is not a scalar function
```

Also tried this in current `master`, got
```
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.ClassCastException: io.prestosql.operator.aggregation.ParametricAggregation cannot be cast to io.prestosql.metadata.SqlScalarFunction
```

To achieve what we want, I had to create sub-query as follows
```
SELECT
	format(
		'%.6f',
		fees
	)
FROM
	(
		SELECT
			SUM( fees / 1e6 ) AS fees
		FROM
			core.rollup
		WHERE
			logdate = '2020-05-01'
	)
```

### PR DESCRIPTION
**Pull request by ArvinZheng**
fix #3829 - allow using aggregations in format() function

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+    @AfterClass(alwaysRun = true)
+    public void teardown()
+    {
+        assertions.close();
+        assertions = null;
+    }
+
+    @Test
+    public void testFormat()
```
Comment (martint) [inline presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java:38]: Rename to `testAggregationInFormat` to clarify this is not a generic test, but we're exercising a specific behavior.

Comment (ArvinZheng) [reply presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java]: will do, thanks for reviewing

File: presto-main/src/main/java/io/prestosql/sql/analyzer/AggregationAnalyzer.java [hunk 2]
```diff
@@ -308,6 +309,12 @@ protected Boolean visitInPredicate(InPredicate node, Void context)
             return process(node.getValue(), context) && process(node.getValueList(), context);
         }
 
+        @Override
+        protected Boolean visitFormat(Format node, Void context)
+        {
+            return node.getArguments().subList(1, node.getArguments().size()).stream().allMatch(expression -> process(expression, context));
```
Comment (martint) [inline presto-main/src/main/java/io/prestosql/sql/analyzer/AggregationAnalyzer.java:315]: This needs to process *all* arguments to `Format`. Otherwise, the analyzer won't realize this is an invalid query:

```
SELECT format(s, sum(v)) FROM (VALUES ('%s', 1)) t(s, v)
```

(`s` must be in the group by clause)

Comment (ArvinZheng) [reply presto-main/src/main/java/io/prestosql/sql/analyzer/AggregationAnalyzer.java:315]: ah...thanks, will fix the code and squash the commits

**Comment by martint** [comment]
Merged, thanks for you contribution!
