### PR TITLE
Ensure transaction cleanup does not fail in transitionToFailed

### LINKED ISSUE #5062: Failure while cleaning up transaction in transitionToFailed
```
presto> create table hive."default".test100("文档" int comment '中文用户ID');
CREATE TABLE
presto> insert into  hive."default".test100 values(111);
INSERT: 1 row

Query 20200903_100942_00046_2xbda, FAILED, 1 node
Splits: 35 total, 35 done (100.00%)
10.72 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200903_100942_00046_2xbda failed: air1:9083: java.net.SocketTimeoutException: Read timed out

presto> insert into  hive."default".test100 values(111);
INSERT: 1 row

Query 20200903_100956_00047_2xbda, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
0.68 [0 rows, 0B] [0 rows/s, 0B/s]

presto> select * from hive."default".test100 ;
 文档 
------
  111 
(1 row)

Query 20200903_101008_00048_2xbda, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0.21 [1 rows, 289B] [4 rows/s, 1.33KB/s]

presto> 

```

### PR DESCRIPTION
**Pull request by dain**
Fixes #5062

### CODE REVIEW

File: presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java [hunk 1]
```diff
@@ -886,12 +886,16 @@ public boolean transitionToFailed(Throwable throwable)
...
+                try {
+                    if (transactionManager.transactionExists(transactionId) && transactionManager.isAutoCommit(transactionId)) {
+                        transactionManager.asyncAbort(transactionId);
+                        return;
+                    }
                 }
-                else {
-                    transactionManager.fail(transactionId);
+                catch (RuntimeException ignored) {
+                    // This shouldn't happen but be safe and just fail the transaction directly
```
Comment (electrum) [inline presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java:896]: Maybe log here. Can this fail due to a race condition?

**Review by electrum — APPROVED** [review]

**Comment by wangfeigithub** [comment]
Will this problem be successful by adding tay catch,
I don't think it's fundamentally solved
