### PR TITLE
Enforce hive.translate-hive-views propertry

### LINKED ISSUE #5623: Configuration property hive.translate-hive-views is partially ignored
```
2020-10-21T09:16:38.363+0200	INFO	main	Bootstrap	
        ↪ hive.translate-hive-views                   false                      false             Experimental: Allow translation of Hive views into Presto views
```

```
presto:default> SELECT * FROM hive_view;
```

Expected:
```
HiveViewNotSupportedException
```

Observed:
```
 a
---
(0 rows)
```

Note that `hive.translate-hive-views` is still used and controls e.g. how a Hive view is presented in `information_schema`.
```
presto:default> select * from information_schema.tables where table_schema = 'default';
 table_catalog | table_schema | table_name | table_type
---------------+--------------+------------+------------
 hive          | default      | a_table    | BASE TABLE
 hive          | default      | hive_view  | BASE TABLE
```

### PR DESCRIPTION
**Pull request by phd3**
Fixes #5623

### CODE REVIEW

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java [hunk 1]
```diff
@@ -1856,6 +1856,10 @@ public void dropView(ConnectorSession session, SchemaTableName viewName)
         return metastore.getTable(new HiveIdentity(session), viewName.getSchemaName(), viewName.getTableName())
                 .filter(ViewReaderUtil::canDecodeView)
                 .map(view -> {
+                    if (!translateHiveViews && !isPrestoView(view)) {
```
Comment (kokosing) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1859]: Can we please have some test for that?

**Comment by laurachenyu** [comment]
Should we throw exception here or just return Optional.empty() like before? I am doing following:
```    public Optional<ConnectorViewDefinition> getView(ConnectorSession session, SchemaTableName viewName)
    {
        if (!filterSchema(viewName.getSchemaName())) {
            return Optional.empty();
        }
        return metastore.getTable(new HiveIdentity(session), viewName.getSchemaName(), viewName.getTableName())
                .filter(ViewReaderUtil::canDecodeView)
                .flatMap(view -> {
                    if (translateHiveViews || isPrestoView(view)) {
                        ConnectorViewDefinition definition = createViewReader(metastore, new HiveIdentity(session), view, typeManager)
                                .decodeViewData(view.getViewOriginalText().get(), view, catalogName);
                        // use owner from table metadata if it exists
                        if (view.getOwner() != null && !definition.isRunAsInvoker()) {
                            definition = new ConnectorViewDefinition(
                                    definition.getOriginalSql(),
                                    definition.getCatalog(),
                                    definition.getSchema(),
                                    definition.getColumns(),
                                    definition.getComment(),
                                    Optional.of(view.getOwner()),
                                    false);
                        }
                        return Optional.of(definition);
                    }
                    return Optional.empty();
                });
    }```

Also, ThriftHiveMetastore:getTable() also used tranlativeHiveViews and we can recover it as well: 
```
                        if (!translateHiveViews
                                && table.getTableType().equals(TableType.VIRTUAL_VIEW.name())
                                && !"true".equals(table.getParameters().get(PRESTO_VIEW_FLAG))) {
                            throw new HiveViewNotSupportedException(new SchemaTableName(databaseName, tableName));
                        }
```

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java (hunk 1 above)
Comment (phd3) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1859]: @kokosing since this is not a session property, I think it's currently hard to test in the product tests without adding a separate config file. But I'm not sure a different configuration is worth the overhead in product test framework. 

Do you have a suggestion on it? or should we add a session property instead?

Comment (kokosing) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1859]: Do we need product tests for that? If we could test it "unit" tests then it would be nice. I guess it might be possible to enhance file based metastore for that. WDYT?

Comment (phd3) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1859]: @kokosing added a test in `AbstractTestHive`, the test seems a bit hacky, since we need to create a table through the client (non-presto code path). But I think it should work for our purpose.

**Comment by phd3** [comment]
@laurachenyu your suggestion also looks good. One difference though is that previously the `isPrestoView` api used hive's Table object, but now we use Presto's object, so that logic would be kind of duplicated. I'm fine with either approaches, @kokosing wdyt?

File: presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java [hunk 2]
```diff
@@ -2556,6 +2557,38 @@ public void testViewCreation()
...
+                        .build())
+                .build();
+
+        metastoreClient.createTable(new HiveIdentity(session), table, testingPrincipalPrivilege(session));
+
+        try (Transaction transaction = newTransaction()) {
+            ConnectorMetadata metadata = transaction.getMetadata();
+            assertThatThrownBy(() -> metadata.getView(session, new SchemaTableName(database, tableName)))
+                    .isInstanceOf(HiveViewNotSupportedException.class)
+                    .hasMessageContaining("Hive views are not supported");
```
Comment (kokosing) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java:2585]: It would be nice add a test where changing config property would actually return a view here.

We have product tests for that, so if adding a test here is problematic then maybe a comment would be enough.

**Review by kokosing — COMMENTED** [review]
I think we should return `Optional.empty()` when hive view is not supported. Otherwise it does make sense to return `Optional` when we fail.

**Comment by phd3** [comment]
Updated based on the suggestions, However, not sure if this is the best way to test. currently, it verifies the logic for `ThriftHiveMetastore` and `FileHiveMetastore` through `TestHive` and `TestHiveFileMetastore`. For `GlueMetastore`, it seems that we haven't implemented or tested the support for the hive view translation so far, so I think that can be done in a separate effort. 

In general, I feel that the testing related to view translation "integration" can be improved using one of the approaches below: 

approach-1: (similar to current updated PR)

- integration logic can be in different `HiveMetastore` implementations.
- need to test them through metastore-specific tests, since they've different codepaths (e.g. a test in AbstractTestHive). If we want to test both the cases (enabled/disabled translation), it requires some amount of refactoring of `AbstractTestHive`.

approach-2:

- Keep all integration related logic in `HiveMetadata` class 
- Test the cases for view-translation enabled and disabled using `FileHiveMetastore`. 

approach-3:

- make the translation enabling switch a session property and test along with product tests by enabling/disabling it. 

I feel approach-2 and approach-3 might be easier, but approach-1 is more exhaustive. however, need to keep in mind that we don't overfit the code-implementation on the ease of testing :)

File: presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java [hunk 3]
```diff
@@ -314,7 +316,15 @@ else if (table.getTableType().equals(EXTERNAL_TABLE.name())) {
     @Override
     public synchronized Optional<Table> getTable(HiveIdentity identity, String databaseName, String tableName)
     {
-        return getTable(databaseName, tableName);
+        Optional<Table> optionalTable = getTable(databaseName, tableName);
```
Comment (electrum) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java:319]: We shouldn't need any view specific logic in the metastore, as the metastore's job is to simply store/retrieve the table metadata. This specific check seems to be a sanity check that the file metastore doesn't contain a Hive view, but that should be impossible since the code is only used by Presto.

File: presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java [hunk 4]
```diff
@@ -343,6 +343,14 @@ public ThriftMetastoreStats getStats()
                     .stopOnIllegalExceptions()
                     .run("getTable", stats.getGetTable().wrap(() -> {
                         Table table = getTableFromMetastore(identity, databaseName, tableName);
+
+                        // Check if hive view is supported
+                        if (!translateHiveViews
```
Comment (electrum) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java:348]: Similar to the other comment, this check should be done in `HiveMetadata` where the translation occurs.

File: presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java [hunk 5]
```diff
@@ -2556,6 +2557,40 @@ public void testViewCreation()
         }
     }
 
+    @Test
+    public void testHiveViewTranslationError()
+    {
+        String tableName = "test_hive_view";
+        ConnectorSession session = newSession();
+        Table table = Table.builder()
```
Comment (electrum) [inline presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java:2565]: We shouldn't need to create a new Hive view here, as these tests already create `presto_test_view` (referenced by the `view` field in this class). It should be enough to call
```java
metadata.getView(session, view);
```

**Review by electrum — CHANGES_REQUESTED** [review]

**Comment by electrum** [comment]
The view translation logic should be independent of the metastore implementation (which is a "dumb" store in terms of view data) and thus so should the tests. The `AbstractTestHive` tests are ancient and it would be nice to deprecate them at some point. Doing this end-to-end with a product test is cleaner.

If it would make it easier, we could add a session property for this, then we could easily change it in the product test.

File: presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java (hunk 3 above)
Comment (phd3) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java:319]: got it, agreed. `ThriftHiveMetastore::getAllViews` also involves usage of view specific config, may be we can move it out too in future.

Comment (electrum) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java:319]: You're right, it's always had logic to do filtering based on `presto_view` flag, but I forgot that it also has special logic based on whether or not we're translating Hive views. In that case, maybe it is required to add more logic to `ThriftHiveMetastore`. Though `FileHiveMetastore` doesn't have any today, so I'd need to be more convinced for that one.

File: presto-docs/src/main/sphinx/connector/hive.rst [hunk 6]
```diff
@@ -306,6 +306,8 @@ Property Name                                      Description
 ``hive.temporary-staging-directory-path``          Controls the location of temporary staging directory that    ``/tmp/${USER}``
                                                    is used for write operations. The ``${USER}`` placeholder
                                                    can be used to use a different location for each user.
+
```
Comment (phd3) [inline presto-docs/src/main/sphinx/connector/hive.rst:309]: as per @mosabua 's comment: https://github.com/prestosql/presto/issues/5623#issuecomment-713733858

Comment (mosabua) [reply presto-docs/src/main/sphinx/connector/hive.rst:309]: thx. looks good.

**Comment by phd3** [comment]
@electrum can you please take a look again? I've simplified the testing based on slack discussion, and just testing with `TestHive` for now. 

Test failures were unrelated, retriggered to get a clean build.

**Comment by findepi** [comment]
> The view translation logic should be independent of the metastore implementation (which is a "dumb" store in terms of view data) and thus so should the tests. The AbstractTestHive tests are ancient and it would be nice to deprecate them at some point. Doing this end-to-end with a product test is cleaner.

I agree, but note that product tests do not involve Glue today (https://github.com/prestosql/presto/issues/5426).
The Hive view support translation layer is independent from metastore, but listing of tables and views _is_.
https://github.com/prestosql/presto/blob/58ee2329fe769042b72974e5b683332e09fc973e/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java#L933-L942

I believe we do need both: product tests for "nice tests" and `AbstractTestHive` to cover Glue too until we do https://github.com/prestosql/presto/issues/5426.

> since this is not a session property, I think it's currently hard to test in the product tests without adding a separate config file. But I'm not sure a different configuration is worth the overhead in product test framework.

> If it would make it easier, we could add a session property for this, then we could easily change it in the product test.

@phd3 @electrum 
adding a new catalog in product tests is really cheap, perhaps just one new file, the catalog configuration.
We should add a session property if we want this to be configurable on per-query basis.
I think this is a good idea, but I really want this **not** to be a result of our testing (in)abilities.

File: presto-docs/src/main/sphinx/connector/hive.rst [hunk 7]
```diff
@@ -306,6 +306,8 @@ Property Name                                      Description
...
+``hive.translate-hive-views``                      Enable translation for hive views. (experimental)            ``false``
```
Comment (electrum) [inline presto-docs/src/main/sphinx/connector/hive.rst:310]: Please capitalize Hive

**Review by electrum — APPROVED** [review]

File: presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHive.java [hunk 8]
```diff
@@ -80,4 +81,17 @@ public void testHideDeltaLakeTables()
...
+    @Test
+    public void testHiveViewTranslationError()
+    {
+        try (Transaction transaction = newTransaction()) {
+            assertThatThrownBy(() -> transaction.getMetadata().getView(newSession(), view))
+                    .isInstanceOf(HiveViewNotSupportedException.class)
+                    .hasMessageContaining("Hive views are not supported");
+
+            // TODO: combine this with tests for successful translation in TestHiveViews product test, it is
+            // currently not possible because translation is not controlled by a session property
```
Comment (findepi) [inline presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHive.java:94]: >  currently not possible ...

this is not true, it is possible (https://github.com/prestosql/presto/pull/5636#issuecomment-715210463)
at most, we decided not to do this

```suggestion
            // TODO: combine this with tests for successful translation in TestHiveViews product test
```

**Comment by phd3** [comment]
Two unrelated failures: #4173 and the one fixed in #5671. Rebasing and rerunning the jobs.

File: presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHive.java (hunk 8 above)
Comment (phd3) [reply presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHive.java:94]: @findepi does this looks better? 

```
// TODO: combine this with tests for successful view translation (currently in TestHiveViews product test)
```

Comment (findepi) [reply presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHive.java:94]: nice, thanks
