### PR TITLE
Quote all identifiers for generated Cassandra query

### LINKED ISSUE #2449: Failed to query Cassandra table with column name that starts with `_`
I get an error when running a simple `SELECT *` from Cassandra table with column that starts with the underscore character.

Here's the error message:
```
[65536] Query failed (#20200109_105522_00005_fy8d8): line 1:10 no viable alternative at character '_' com.datastax.driver.core.exceptions.SyntaxError: line 1:10 no viable alternative at character '_'
```

I'm using PrestoSQL v327 with JDBC driver v327 with Cassandra v3.11.3

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #2449

Only alphanumeric and underscore are allowed as the identifier in Cassandra.
I guess we can quote all identifiers without the current conditions, but I added this logic to minimize the diff.

### CODE REVIEW

File: presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java [hunk 1]
```diff
@@ -333,12 +331,12 @@ public ConnectorInsertTableHandle beginInsert(ConnectorSession session, Connecto
...
         List<CassandraColumnHandle> columns = cassandraSession.getTable(schemaTableName).getColumns();
-        List<String> columnNames = columns.stream().map(CassandraColumnHandle::getName).map(CassandraCqlUtils::validColumnName).collect(Collectors.toList());
+        List<String> columnNames = columns.stream().map(CassandraColumnHandle::getName).collect(Collectors.toList());
         List<Type> columnTypes = columns.stream().map(CassandraColumnHandle::getType).collect(Collectors.toList());
 
         return new CassandraInsertTableHandle(
-                validSchemaName(table.getSchemaName()),
-                validTableName(table.getTableName()),
+                table.getSchemaName(),
+                table.getTableName(),
```
Comment (findepi) [inline presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java]: Please maybe extract a separate commit like "Retain actual names in CassandraInsertTableHandle"

File: presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java [hunk 2]
```diff
@@ -92,14 +95,14 @@ public CassandraPageSink(
             this.toCassandraDate = value -> LocalDate.fromDaysSinceEpoch(toIntExact(value));
         }
 
-        Insert insert = insertInto(schemaName, tableName);
+        Insert insert = insertInto(validSchemaName(schemaName), validTableName(tableName));
```
Comment (findepi) [inline presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java]: This would belong to "Retain actual names in CassandraInsertTableHandle" if you extract it

File: presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java [hunk 3]
```diff
@@ -76,6 +76,10 @@ private static String validIdentifier(String identifier)
         if (keywords.contains(identifier.toUpperCase(ENGLISH))) {
             return quoteIdentifier(identifier);
         }
+
+        if (identifier.startsWith("_") || identifier.endsWith("_")) {
+            return quoteIdentifier(identifier);
```
Comment (findepi) [inline presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java]: In the description you wrote

> Only alphanumeric and underscore are allowed as the identifier in Cassandra.

but the logic here is different.

Did you mean something like

```
if (!identifier.matches("[a-z]([a-z0-9_]*[a-z0-9])?") {
    return quoteIdentifier(identifier);
}
```

this would not only impl want you describe (quote everything that contains non-underscore, non-alphanumeric characters), but also

* quote names starting with digit (i'm just guessing this isn't legal either)
* quote empty names (eliminating existing check at the beginning of `validColumnName` method)
* quote non-lowercase names (eliminating existing check at the beginning of `validIdentifier` method)

(of course, such Pattern should be compiled as static field)

Comment (ebyhr) [reply presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java]: Sorry, my description was insufficient. Cassandra throws an exception if an identifier contains non-underscore symbols. This case happens when Presto tries to create an table. 
So, my intent was "allowed but it is needed to be quoted in some cases". 

Exactly, my current commit misses some cases (e.g. starting/ending with digit). Let me update.

Comment (findepi) [reply presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java]: btw, can we quote unconditionally?

i know you've considered that, but I don't know why you abandoned this idea.

Comment (ebyhr) [reply presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java]: It seems like existing tests depend on the condition (I don't think the test is important), so I wanted to confirm more detail. I'll investigate it again before updating this PR.
