### PR TITLE
Fix UI redirect with proxy

### LINKED ISSUE #2908: New WebUI Authentication Manager Breaks Forwarded HTTPS
We use a load balancer in front of Presto to handle HTTPS.  The load balancer forwards to Presto on port 8080.  We enable `http-server.authentication.allow-forwarded-https` to support authentication in this scenario.

Running a snapshot of master, I am not able to reach Presto through the load balancer.  Browsing to `https://presto.domain.com` delivers a 303 status code, redirecting to `https://presto.domain.com:80/ui`.  This is incorrect, as no one is listening on port 80.

### PR DESCRIPTION
**Pull request by dain**
Fixes #2908

### CODE REVIEW

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java [hunk 1]
```diff
@@ -318,21 +319,10 @@ private static String getRedirectLocation(HttpServletRequest request, String pat
...
-        else {
-            // forwarded
-            builder = uriBuilder()
+        HttpUriBuilder builder = uriBuilder()
                     .scheme(firstNonNull(emptyToNull(request.getHeader(X_FORWARDED_PROTO)), request.getScheme()))
-                    .host(request.getHeader(X_FORWARDED_HOST));
-            getForwarderPort(request).ifPresent(builder::port);
-        }
+                    .host(firstNonNull(emptyToNull(request.getHeader(X_FORWARDED_HOST)), request.getServerName()))
+                    .port(getForwarderPort(request).orElse(request.getServerPort()));
```
Comment (findepi) [inline presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: If there is
```
X-Forwarder-Proto https
X-Forwarder-Host my-load-balancer.local
```

then using 8080 (in absence of `X-Forwarded-Port`) seems unreasonable.
Using https' default would make more sense to me. 
(This is why i wrote the code this way.)

@electrum?

**Comment by findepi** [comment]
Please add a test to `io.prestosql.server.TestServer#testRedirectToUi` and maybe enhance the `io.prestosql.server.ui.TestWebUi#assertRedirect(okhttp3.OkHttpClient, java.lang.String, java.lang.String, boolean)` method.

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java (hunk 1 above)
Comment (dain) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: I tried looking at the spec, but it doesn't say anything useful. So I suggest we just make sure that AWS, GCP, and Azue LBs work:
* ALB: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html
* GCP: https://cloud.google.com/load-balancing/docs/https
* Asure: https://docs.microsoft.com/bs-latn-ba/azure/frontdoor/front-door-http-headers-protocol
One thing interesting, it looks like the `X-Forwarded-Host` header can contain a port.

Comment (findepi) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: Interesting. Seems AWS ALB, GCP don't document `X-Forwarded-Host` at all, so if we want to support that, we need to find out the load balancer IP address differently. For example, GCP suggests it puts a bunch of different addresses in `X-Forwarded-For` and one _could be_ the load balancer's IP.

... I am probably missing something obvious, this doesn't sound convincing to myself.

Comment (veysiertekin) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: Hi,

We are facing same problem as well at Alicloud SLB which does not support `X-Forwarded-Host`. Just provides `X-Forwarded-For` and `X-Forwarded-Proto`. Somehow `https` should be activated when `X-Forwarded-Proto` present.

BTW, i have tried this PR, but situation seems persistent.

Comment (dain) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: @findepi and @veysiertekin I don't think they provide `X-Forwarded-Host` because it isn't needed.  For those systems, the host is unchanged from the host header in the request, because the LB run on the same host just on a different port.

Comment (findepi) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: @dain  in AWS ALB cases, the host (machine) is definitely separate. But, maybe, we get it in the `Host` header and that's why we don't need it?

File: presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java [hunk 2]
```diff
@@ -344,13 +344,115 @@ private static void assertRedirect(OkHttpClient client, String url, String redir
...
                     .url(url)
-                    .header(X_FORWARDED_PROTO, "https")
+                    .header(X_FORWARDED_PROTO, "test")
                     .header(X_FORWARDED_HOST, "my-load-balancer.local")
-                    .header(X_FORWARDED_PORT, "443")
+                    .header(X_FORWARDED_PORT, "123")
                     .build();
             try (Response response = client.newCall(request).execute()) {
                 assertEquals(response.code(), SC_SEE_OTHER);
-                assertEquals(response.header(LOCATION), "https://my-load-balancer.local:443/" + redirectLocation.replaceFirst("^([^/]*/){3}", ""));
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java]: i deliberately used .replace instead of using uri builder. 
Replace is simplistic, so it's obvious what the expected value is.
With uri builder used in the test and in the code under test, it's not as obvious.

File: presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java [hunk 3]
```diff
@@ -344,13 +344,115 @@ private static void assertRedirect(OkHttpClient client, String url, String redir
...
+                    .url(url)
+                    .header(X_FORWARDED_HOST, "my-load-balancer.local")
+                    .build();
+            try (Response response = client.newCall(request).execute()) {
+                assertEquals(response.code(), SC_SEE_OTHER);
+                assertEquals(
+                        response.header(LOCATION),
+                        uriBuilderFrom(URI.create(redirectLocation))
+                                .host("my-load-balancer.local")
+                                .defaultPort()
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java]: Isn't in this case simply `http://my-load-balancer.local/`? we could use constant here

File: presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java [hunk 4]
```diff
@@ -344,13 +344,115 @@ private static void assertRedirect(OkHttpClient client, String url, String redir
...
+                                .toString());
+            }
+
+            request = new Request.Builder()
+                    .url(url)
+                    .header(X_FORWARDED_PORT, "123")
+                    .build();
+            try (Response response = client.newCall(request).execute()) {
+                assertEquals(response.code(), SC_SEE_OTHER);
+                assertEquals(response.header(LOCATION), redirectLocation);
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java]: Add a comment like `// X-Forwarded-Port not recognized as valid forwarding`

**Comment by findepi** [comment]
Is this the logic that happens when forwarding happens on the resource handler level?

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java (hunk 1 above)
Comment (dain) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: From the original issue, his headers are:
```
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Host: presto.domain.net
```
In this case, we change the protocol, and port, but not the host which was `presto.domain.net`.

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java [hunk 5]
```diff
@@ -371,15 +357,30 @@ private static String parseJwt(byte[] hmac, String jwt)
...
-    private static Optional<Integer> getForwarderPort(HttpServletRequest request)
+    private static HttpUriBuilder toUriBuilderWithForwarding(HttpServletRequest request)
     {
-        if (!isNullOrEmpty(request.getHeader(X_FORWARDED_PORT))) {
-            try {
-                return Optional.of(parseInt(request.getHeader(X_FORWARDED_PORT)));
-            }
-            catch (ArithmeticException ignore) {
+        HttpUriBuilder builder;
+        if (isNullOrEmpty(request.getHeader(X_FORWARDED_PROTO)) && isNullOrEmpty(request.getHeader(X_FORWARDED_HOST))) {
```
[the remark this answers is not in the document]
Comment (dain) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: When did we decide that the `X_FORWARDED_HOST` is not an "activator".  We decided that `X_FORWARDED_PROTO` alone without the other two doesn't make much sense.  I am fine making it an activator also, since none of the LBs seem to do that, so it shouldn't matter.  BTW the port header isn't part of the spec.  The `X_FORWARDED_HOST` header is documented here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java [hunk 6]
```diff
@@ -371,15 +357,30 @@ private static String parseJwt(byte[] hmac, String jwt)
...
+            builder = uriBuilder()
+                    .scheme(request.getScheme())
+                    .host(request.getServerName())
+                    .port(request.getServerPort());
+        }
+        else {
+            // forwarded
+            builder = uriBuilder()
+                    .scheme(firstNonNull(emptyToNull(request.getHeader(X_FORWARDED_PROTO)), request.getScheme()))
+                    .hostAndPort(HostAndPort.fromString(firstNonNull(emptyToNull(request.getHeader(X_FORWARDED_HOST)), request.getServerName())));
```
[the remark this answers is not in the document]
Comment (dain) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: I don't understand.  The `Host` and `X-Forwarded-Host` header both allow an optional port.  If the port is not specified, the default port is used.

File: presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java (hunk 2 above)
Comment (dain) [reply presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java]: I am confused by this statement.  The regex to replace sub parts in the middle of the string would be very complex.  I find the new code really clear:
```
uriBuilderFrom(URI.create(redirectLocation))
                    .scheme("test")
                    .host("my-load-balancer.local")
                    .port(123)
                    .toString());
```
It literally says, take the redirect location, and replace some bits.

File: presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java (hunk 3 above)
Comment (dain) [reply presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java]: No. The code is `uriBuilderFrom`, so the subsequent lines are "replacements".

**Comment by findepi** [comment]
> There used to be a JAX-RS resource that performed the redirection from '/', but that is all part of the `FormWebUiAuthenticationManager` code now.

Do we now cover the cases that JAX-RS resource used to cover?

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (electrum) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: It's probably best to make any of these an activator. I don't see a downside in doing so.

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java [hunk 7]
```diff
@@ -371,15 +357,30 @@ private static String parseJwt(byte[] hmac, String jwt)
...
+
+            if (!isNullOrEmpty(request.getHeader(X_FORWARDED_PORT))) {
```
Comment (electrum) [inline presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: Could simplify this to
```java
Optional.ofNullable(emptyToNull(request.getHeader(X_FORWARDED_PORT)))
        .map(Ints::tryParseInt)
        .ifPresent(builder::port);

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (electrum) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: I think this should be
```java
.hostAndPort(HostAndPort.fromString(request.getHeader(HOST)))
```
We don't want to add the port number unless the original request had one. Though, what happens if there's no `Host` header? Is that legal?

File: presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (electrum) [reply presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java]: Same, I think this should be using `request.getHeader(HOST)`
